runhouse/rns/function.py, runhouse/rns/run_module_utils.py, runhouse/servers/grpc/unary_server.py
Move adding relative path to sys.path from `RunModule` to `_get_fn_name`. In [multi gpu tutorial example](https://github.com/run-house/tutorials/blob/main/t04_Distributed/p01a_accelerate_multigpu_example.py), where there is nested function calls, only the external relative path (`tutorials/t04_Distributed`) was added to sys.path, and not relative path for the internal rh function (`accelerate/examples`)
=> Correctly add relative path to sys.path

README.md, docs/index.rst, docs/overview/accessibility.rst, docs/overview/compute.rst, docs/overview/data.rst, docs/rh_primitives/blob.rst, docs/rh_primitives/cluster.rst, docs/rh_primitives/folder.rst, docs/rh_primitives/function.rst, docs/rh_primitives/package.rst, docs/rh_primitives/resource.rst, docs/rh_primitives/table.rst, docs/secrets/vault_secrets.rst, runhouse/rns/folders/folder.py, runhouse/rns/function.py, runhouse/rns/packages/package.py
move majority of API usage code snippets out from architecture overview, into corresponding Python API sections, in an effort to consolidate useful code into relevant section.
Currently, API usage is located under API docs, and accessible by scrolling or on the right sidebar.
=> Reorganize API usage docs

runhouse/rns/hardware/cluster.py, tests/test_cluster.py
`gpu.on_same_cluster(resource)` returns whether or not `resource` is on `gpu` cluster
=> Add on_same_cluster

README.md, runhouse/main.py, runhouse/rns/function.py, runhouse/rns/hardware/cluster.py, runhouse/rns/run_module_utils.py, runhouse/servers/grpc/unary.proto, runhouse/servers/grpc/unary_client.py, runhouse/servers/grpc/unary_pb2.py, runhouse/servers/grpc/unary_pb2_grpc.py, runhouse/servers/grpc/unary_server.py, tests/test_function.py
_Current behavior_: By default, Runhouse passes in fractional resources `{"num_cpus": 0.0001, "num_gpus": 0.0001}` when calling `ray.remote()` on a particular Function. This results in the scheduling and queueing not always working properly,  since we are basically telling Ray that each job doesn't need any resources.  
This change gives users control over the resources allocated to a particular Function, by adding a`resource` parameter to the `Function` object. Users can specify `num_cpus` (number of CPU cores to reserve for the task) or `num_gpus` (number of GPUs to reserve).
=> add `resources` property for Function object to pass into ray.remote

runhouse/rns/rns_client.py
in Windows, if Python path is `C:\\Python`, then it can throw RecursionError on startup.
=> Prevent RecursionError in import (for Windows, path dependent)

requirements.txt, runhouse/main.py, runhouse/rns/envs/conda_env.py, runhouse/rns/envs/env.py, runhouse/rns/folders/folder.py, runhouse/rns/hardware/cluster.py, runhouse/rns/hardware/cluster_factory.py, runhouse/rns/rns_client.py, runhouse/rns/run.py, runhouse/servers/http/http_client.py, setup.py, tests/conftest.py, tests/test_blob.py, tests/test_cluster.py, tests/test_env.py, tests/test_folder.py, tests/test_function.py, tests/test_obj_store.py, tests/test_package.py, tests/test_rns.py, tests/test_run.py, tests/test_secret.py, tests/test_table.py
Add support for BYO clusters with passwords. These clusters
* use paramiko for running SSH commands
* use fsspec for file transfers between local <-> cluster and cluster <-> cluster
Note: to run tests without password cluster, add `-k "not [password_cluster]"` to pytest command (ex/ `pytest test_function.py -v -m clustertest -k "not [password_cluster]"`)
Note: running `python -c` through cli or `cluster.run_python` is finicky due to bsah cli quoting.
=> Support clusters w/ passwords

docs/conf.py, docs/debugging_logging.rst
Fixes a link typo that was breaking the JSON docs building - was ignoring subfolders `/python` `/tutorials` etc.
=> Typo breaking JSON docs

runhouse/main.py, runhouse/rns/hardware/cluster.py
This PR replaces usage of python with python3 in command `python -m runhouse.servers.http.http_server`
Also adds logging around subprocess executing this command to log relevant error if execution is unsuccessul.
=> Use python3 cmd to start http_server + logging when cmd not found

runhouse/rns/folders/folder.py, runhouse/rns/function.py, runhouse/rns/hardware/cluster.py, runhouse/rns/packages/package.py, runhouse/rns/utils/env.py, runhouse/rns/utils/hardware.py, runhouse/servers/http/http_client.py, tests/conftest.py, tests/test_cluster.py
- Add ssh_proxy support, except for folders (due to sshfs issues). cluster.run, cluster.rsync, and forming tunnels all work through SSHCommandRunner.
- Create a subclass of SSHCommandRunner for cleanliness and richer options.
- Tweak working_dir behavior slightly more
Pending - allowing more ssh options, replace cluster.ssh with CommandRunner.
=> Proxy tunnel support, including subclassing SSHCommandRunner

docs/_ext/json_globaltoc.py, docs/conf.py, docs/tutorials/examples/distributed.rst, runhouse/servers/http/http_client.py
- Adds a custom extension to sphinx to append a global TOC to JSON output
- Updates the distributed example to use `:class: code-output` for clarifying output code blocks
- Replaces image blobs with URLs in large `inference.rst` file
=> Sphinx JSON builder with global TOC

runhouse/rns/packages/package.py
There is an edge case in [`check_call`](https://docs.python.org/3/library/subprocess.html#subprocess.check_call) where, if the process was not able to be started, the underlying exception is propagated. In my case, `nvidia-smi` is not installed, so my `rh.function()` call crashed with a `FileNotFoundError`.
The relevant portion of the docs (emphasis mine):
> Run command with arguments. Wait for command to complete. If the return code was zero then return, otherwise raise [CalledProcessError](https://docs.python.org/3/library/subprocess.html#subprocess.CalledProcessError). The [CalledProcessError](https://docs.python.org/3/library/subprocess.html#subprocess.CalledProcessError) object will have the return code in the [returncode](https://docs.python.org/3/library/subprocess.html#subprocess.C …
=> Handle case where `nvidia-smi` is not installed

README.md, docs/notebooks/basics/accessibility.ipynb, docs/notebooks/basics/compute.ipynb, docs/notebooks/basics/data.ipynb, docs/notebooks/examples/distributed.ipynb, docs/notebooks/examples/training.ipynb, docs/tutorials/api/accessibility.rst, docs/tutorials/api/compute.rst, docs/tutorials/api/data.rst, docs/tutorials/examples/distributed.rst, docs/tutorials/examples/inference.rst, docs/tutorials/examples/training.rst, docs/tutorials/quick_start.rst
- Changes `run-house.readthedocs` links to `run.house/docs`
- Adds `code-output` class to parsed literals
=> Updating docs links and code output syntax

docs/api/python/cluster.rst, runhouse/resources/hardware/sagemaker_cluster.py, runhouse/scripts/sagemaker_cluster/refresh-ssm-session.sh, runhouse/scripts/sagemaker_cluster/start-ssm-proxy-connection.sh
Improve the flexibility for connecting to SageMaker clusters by: 
- Maintaining an authorized keys list with public keys stored in S3
- Copying the authorized keys file onto the cluster when connecting
- Generating a fresh key pair and adding the public key to the authorized list If user with the relevant SageMaker role does not already have one
=> SSH Flexibility for SageMaker clusters

runhouse/main.py, runhouse/resources/hardware/cluster.py, runhouse/rns/defaults.py, runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py
Example usages:
runhouse start --custom_server_host 0.0.0.0
runhouse restart --custom_server_host 0.0.0.0
python -m runhouse.servers.http.http_server --host 0.0.0.0
=> Support an optional `host` parameter for the start and restart commands.

runhouse/resources/function.py, runhouse/resources/hardware/sagemaker_cluster.py, runhouse/resources/module.py, runhouse/resources/resource.py
Some sagemaker bugs:
- not creating session with profile
- not taking up the cluster if no address found in check_server
- Don't fail if role or profile are not found to create session when on the cluster
Remove "resources" from function, which is obsolete.
Don't let env save if it has name Env.DEFAULT_NAME. This clearly needs more work (e.g. not setting the default name directly, but rather implicitly) but for now is ok.
Fix alt_options so if an option is specified which is not in the config, it counts as a miss.
One thing we still need is to run `/opt/conda/bin/conda init` somewhere in the setup flow. Not sure where that should be (I don't think it should be in the script, because conda may not be present inside the user's docker image). Thoughts @jlewitt1 ?
=> Bugfixes (Sagemaker, Function, Env)

runhouse/resources/blobs/blob.py, runhouse/resources/blobs/file.py, runhouse/resources/module.py, tests/test_blob.py
Fixes two bugs in the current `.to(cluster, dest_path)` function for File:
* we set the folder of the `dest_path` to have the path of the `dest_path`, rather than the parent of `dest_path`
* we send the folder to `cluster`, which includes all contents of the file's parent folder, rather than the file alone
The intended goal of `.to(cluster, dest_path)` is to write the contents of the local file to the `dest_path` file.
This can further be improved in the future by directly syncing over files without needing to hold the contents in Python memory.
=> Fix file .to bugs

.gitignore, tests/conftest.py
- Update the location of docker_user_passwd to be under ~/.rh/secrets
- Update the ports to correspond to the Dockerfile
- Remove docker_user_passwd from .gitignore
=> Update the Docker test setup

runhouse/servers/http/auth.py, runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py, runhouse/servers/obj_store.py, runhouse/servers/servlet.py
**Move the den auth / resource validation out of the HTTP server and into the object store**
Make `AuthCache` into an actor on the cluster which holds a basic cache. 
The `AuthCache` class itself is the actor: when a new request comes in with a token, pass in to the actor's `add_user` method which loads down resources it has access to and stores it in the cache.
When functions are called on the cluster, validate token (if den auth is enabled) and first check cache to validate the user's access. 
------
Continue using a validator decorator (`validate_cluster_access`) to validate the user's access to the cluster if den auth is enabled before continuing with API logic. If the user has write access to the cluster will be given access to all resources on the cluster by default. 
For function …
=> Auth Cluster Cache

runhouse/resources/envs/env.py
Example: 
```
rh.env(
reqs=["pytest"],
working_dir=None,
setup_cmds=[
f'mkdir -p ~/.rh; echo "token: {rh.configs.get("token")}" > ~/.rh/config.yaml'
],
name="base_env")```
=> Support running shell commands in env

runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/utils.py, tests/conftest.py, tests/test_clusters/test_pwd_cluster.py, tests/test_obj_store.py
Uses pexepct to direct passwords to the console for clusters which require them, eliminating fsspec and paramiko from the connection flow, and also giving us a printable string to debug password cluster connection issues with. Everything now flows through the SkyPilot SSHCommandRunner, which I've also updated our fork of.
Also adds an attempt at a simple password test suite. Tests pass for docker and cpu password clusters.
...I have no idea what's going on with the commits. Help.
=> Use Pexpect for password clusters instead of paramiko and fsspec

tests/conftest.py, tests/test_blob.py, tests/test_clusters/test_cluster.py, tests/test_env.py, tests/test_folder.py, tests/test_package.py, tests/test_secret.py, tests/test_table.py
Use `default_fixtures` based on the provided test level instead of the `cpu_clusters` decorator
=> Remove deprecated pytest decorator

tests/conftest.py, tests/test_resource_sharing.py
- Do not rebuild test image if one already exists 
- Add pytest option to force rebuild the image 
- Refactoring sharing tests - create a fixture for loading and sharing shared resources, and always run the sharing unit tests in a local docker container instead of spinning up an ondemand cluster
=> Pytest fixture cleanups / updates

runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/cluster_factory.py, runhouse/resources/hardware/on_demand_cluster.py, runhouse/resources/hardware/sagemaker_cluster.py, runhouse/resources/hardware/utils.py, runhouse/servers/http/http_server.py, tests/conftest.py, tests/test_resources/test_clusters/conftest.py, tests/test_resources/test_clusters/test_cluster.py
- Enable simultaneous docker cluster tests
- Introduce ssh_port and client_port in Cluster to avoid collisions on localhost:22
- Docker clusters now connect over ssh tunnels if connection_type="ssh" instead of opening ports and sidestepping ssh (more realistic)
- Fix passthrough bugs in cluster factories
- Remove PARAMIKO connection type, obsolete 
Module tests pass with LOCAL
=> Enable simultaneous cluster tests

tests/README.md, tests/test_resources/test_clusters/conftest.py
As explained in `tests/README.md`, users generally have a sky-key set up and we can use that for communication with local Docker clusters.
=> Change default keypair keypath for Docker-based local tests.

runhouse/rns/rns_client.py, tests/conftest.py, tests/test_resources/test_clusters/test_cluster.py
There was a bug in the `test_account` context manager / fixture that led to the config not being properly updated globally. This led to Resources being created with the wrong account in test usages.
=> Fixing test account context manager to correctly update account in global cache.

tests/conftest.py, tests/test_resources/conftest.py, tests/test_resources/test_clusters/conftest.py, tests/test_resources/test_clusters/test_cluster.py
**To Test (all passing)**: 
```
pytest -v tests/test_resources/test_clusters/test_cluster.py --level local
```
After the addition of the telemetry cluster, we have a lot of local Docker clusters running. When running the cluster tests with the addition of @DenisYay 's telemetry test, my Docker VM begins to OOM because there are too many containers running on it at once.
In an effort to get rid of this problem, I introduce two function scoped fixtures, `local_docker_cluster_public_key_logged_out` and `local_docker_cluster_public_key_logged_in`, that are _actually_ the same container under the hood and simply log the user in and out. I introduce some basic tests for these that ensure that we are correctly "logged in". These additional simple tests are really useful and would have uncovered …
=> Cleaning up local Docker cluster fixtures.

tests/test_resources/test_clusters/conftest.py, tests/test_resources/test_resource.py, tests/test_servers/test_http_server_with_auth.py
I introduce a sharing test for sharing resources generically with another user. This uses another local cluster that is logged in as a test user.
=> Add generic resource sharing test utilizing test account cluster fixture.

runhouse/docker/slim/password-file-auth/Dockerfile, runhouse/docker/slim/public-key-auth/Dockerfile, runhouse/resources/hardware/cluster.py
add separate fixture for local tls with nginx testing
Fix global ssh tunnel cache to use port as well. (#149)
We use a global dictionary to cache open ssh connections to particular
addresses. However, for local tests where several connections are running
locally on localhost, the cache would incorrectly hit.
Add an end-to-end test for a local docker cluster with telemetry enabled (#142)
Disable telemetry by default in the local docker public key cluster
Add ServerModule Tests (#151)
update nginx tests for local docker
Merge remote-tracking branch 'origin/main' into telemetry-nginx-docker-updates
update nginx local tests to use separate containers for http / https
set up client port for nginx fixtures
=> Update Dockerfile for Sudo support + Nginx

tests/conftest.py, tests/test_resources/test_clusters/conftest.py, tests/test_servers/test_http_server.py, tests/test_servers/test_http_server_with_auth.py
- Get rid of "base_cluster" in test_http_server.py, as it runs restart_server twice in each test, and doesn't allow us to dynamically swap in other cluster levels to test.
- Default resync_rh=False when creating cluster fixtures, just to save time between tests.
- Fix a few test idempotence bugs in test_http_server.py and test_http_server_with_auth.py
test_http_server.py passes
=> Get rid of base_cluster

runhouse/servers/http/certs.py, runhouse/servers/http/http_client.py, runhouse/servers/http/http_server.py, runhouse/servers/nginx/config.py, tests/conftest.py, tests/test_resources/test_clusters/conftest.py, tests/test_servers/conftest.py, tests/test_servers/test_nginx.py
update support for nginx / telemetry for running on local docker
add separate fixture for local tls with nginx testing
update nginx tests for local docker
update nginx local tests to use separate containers for http / https
set up client port for nginx fixtures
update support for nginx / telemetry for running on local docker
add separate fixture for local tls with nginx testing
=> update support for nginx / telemetry for running on local docker

pytest.ini, runhouse/resources/hardware/cluster.py, tests/conftest.py, tests/test_resources/test_clusters/test_cluster.py, tests/test_resources/test_resource.py
Users will now need to add `--ignore-filters` to their pytest commands in order to run tests as they were before. For example `pytest -s -v tests/test_resources/test_cluster.py --level local --ignore-filters`.
`pytest -v --level local` passes.
=> Enable functionality for marking tests by their level and filter these in collection.

runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/cluster_factory.py, runhouse/resources/hardware/utils.py, runhouse/servers/http/http_client.py, runhouse/servers/http/http_server.py, tests/test_servers/test_http_client.py, tests/test_servers/test_http_server.py
Bugfixes to enable HTTPS/Den Auth service sharing, and general robustness.
- cluster.address is now a property and no longer duplicative with cluster.ips.
- Move rh_version check to between http_client and http_server, and happen over RPC
- Fix warnings about aws credentials and server_port not being in open_ports
test_modules.py, test_server/, and test_cluster.py all pass with LOCAL.
=> Cluster bugfixes / Move rh version mismatch check

runhouse/resources/envs/env_factory.py, runhouse/resources/envs/utils.py, runhouse/resources/hardware/cluster.py, tests/conftest.py, tests/test_resources/test_envs/assets/test_conda_env.yml, tests/test_resources/test_envs/conftest.py, tests/test_resources/test_envs/test_env.py
* added fixtures for various types of base and conda envs
* refactored env tests to subclass resource test and reuse tests across fixtures
* usage: `pytest -v --level "minimal" tests/test_resources/test_envs/test_env.py`
next steps for env testing
* conda docker container working to enable local tests
* cut down on testing time
=> Refactor env tests and add env fixtures

tests/conftest.py, tests/fixtures/local_docker_cluster_fixtures.py, tests/test_resources/conftest.py, tests/test_resources/test_clusters/test_cluster.py, tests/test_resources/test_clusters/test_on_demand_cluster/conftest.py, tests/test_resources/test_clusters/test_sagemaker_cluster/conftest.py, tests/test_resources/test_envs/conftest.py, tests/test_resources/test_envs/test_env.py, tests/test_resources/test_modules/test_blobs/conftest.py, tests/test_resources/test_modules/test_blobs/test_blob.py, tests/test_resources/test_modules/test_folders/conftest.py, tests/test_resources/test_modules/test_folders/test_packages/conftest.py, tests/test_resources/test_modules/test_tables/conftest.py, tests/test_resources/test_resource.py, tests/test_servers/test_http_server.py
When setting up the fixture list within a class, we were doing something along the lines of:
```
class TestClass:
UNIT = {"cluster": [local_cluster]}
```
This requires an import of `local_cluster` from conftest. Turns out, this causes session scoped fixtures to be recomputed (https://github.com/pytest-dev/pytest/issues/3217). It's bad practice to import from conftest in the first place. So, I changed the fixtures that run `getfixturevalue` to just use the string argument, and we can avoid importing, and rely on pytest to set up the fixtures correctly. Now we set up fixtures like so:
```
class TestClass:
UNIT = {"cluster": ["local_cluster"]}
```
Moreover... if a fixture is defined in a nested `conftest.py`, and imported in the global `conftest.py`, then there can be conflicts. The way …
=> Avoid ever importing fixtures from conftest.

docs/tutorials/examples/inference.rst
Adds missing `alt` tags to `img` elements in the Inference Tutorial
=> Add alt tags to inference tutorial

tests/test_resources/test_modules/test_functions/test_function.py
Passing an env as a part of `.to` overrides the entire existing env initialized as part of the function definition. This is, for now, expected behavior.
Moreover, when initializing from_config, we need to explicitly set the working_dir else it'll be set to None, and the current function will not be pushed up. 
**Testing**: `pytest -v --level local -k "TestFunction"`
=> Fix test_from_config to correctly use existing env.

runhouse/globals.py, runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/sagemaker_cluster.py, runhouse/resources/hardware/utils.py, tests/fixtures/local_docker_cluster_fixtures.py
Run local tests, but individually (when running together we still get some cluster issues):
Server tests: `pytest -v --level local -k "not TestFunction and not TestEnv and not TestCluster and not TestResource`
Cluster & Resource: `pytest -v --level local -k "TestCluster or TestResource"`
Function: `pytest -v --level local -k "TestFunction"`
=> Fix use of open_cluster_tunnels cache to account for dead connections.

tests/conftest.py
Temporarily fixes a bug in test_module when running with unit and docker container is being created, but we should
fix this for real when we introduce proper Module unit tests.
=> Change the default "unit" cluster fixtures to not use Docker

runhouse/resources/module.py, runhouse/resources/resource.py, runhouse/scripts/sagemaker_cluster/launch_instance.py
We weren't catching ModuleNotFoundErrors to default to the signature in cases where the function's
package is not present, only AttributeErrors, which is the case when a Module's backing code isn't
present.
=> Fix small bug with reloading module from name

docs/api/python/cluster.rst, runhouse/resources/hardware/cluster_factory.py
* move out factory functions to the beginning, similar to the way it's done for envs
* move cluster auth+verification down a sub level
* convert a link to hyperlink
=> Update some cluster docs organization

docs/api/python.rst
runs no longer user facing following addition of rh.module and provenance
=> Remove Runs from Python API Docs

runhouse/servers/http/http_client.py, runhouse/servers/http/http_server.py, tests/test_servers/test_http_server.py
no longer needed after converting secrets to a resource type. can just use general resource endpoint
=> Remove add_secrets endpoint

runhouse/resources/function.py, runhouse/resources/resource.py, runhouse/rns/utils/api.py
Store basic access info in resources. Make users an optional argument to resource.share, allowing users to control default visibility (i.e. share with the world) via resource.share().
=> Fix basic access flow in resources

runhouse/resources/folders/folder.py
was running into connection error when trying to fetch file/folder contents on testing docker container. adding port to the data config resolves this error.
=> Add ssh port to folder resource's fsspec fs

runhouse/__init__.py, runhouse/resources/functions/__init__.py, runhouse/resources/functions/function.py, runhouse/resources/functions/function_factory.py, runhouse/resources/resource.py
* deprecate access_type, with warning, instead of BC-breaking (remove in future release)
* update function signatures w/ deprecated arguments to hide those arguments
* correct funciton_factory file name to function_factory
=> Update deprecations and corresponding fn signatures

runhouse/resources/functions/aws_lambda.py
When creating a lambda from a callable python function, the paths_to_code were not extracted correctly.
=> Bugfix - exctract path to code correctly from pointers

docs/api/python/secrets.rst, runhouse/resources/secrets/provider_secrets/anthropic_secret.py, runhouse/resources/secrets/provider_secrets/api_key_secret.py, runhouse/resources/secrets/provider_secrets/cohere_secret.py, runhouse/resources/secrets/provider_secrets/huggingface_secret.py, runhouse/resources/secrets/provider_secrets/langchain_secret.py, runhouse/resources/secrets/provider_secrets/openai_secret.py, runhouse/resources/secrets/provider_secrets/pinecone_secret.py, runhouse/resources/secrets/provider_secrets/provider_secret.py, runhouse/resources/secrets/provider_secrets/providers.py, runhouse/resources/secrets/provider_secrets/wandb_secret.py, tests/conftest.py, tests/test_resources/test_secrets/conftest.py, tests/test_resources/test_secrets/test_secret.py
Add secrets for new providers (anthropic, cohere, langchain, openai, pinecone, wandb). These secrets are all of the type `ApiSecretKey`, which is similar to the base `ProviderSecret` class, with the expected single value dict `{"api_key": "value..."}`, and env var `[PROVIDER]_API_KEY`, and by default we set env vars in `write()` and `to()` functions.
=> Add additional provider secrets

runhouse/resources/secrets/provider_secrets/provider_secret.py, runhouse/servers/http/http_client.py, tests/test_resources/test_secrets/test_secret.py
Previously, when sending secrets to a cluster, values would be included in the obj store through the `put_resource` call.
In this PR, update the default behavior for whether or not to include `values` for the secret in the obj store.
* Values will be saved to obj store if no path or env is provided in the `.to()` call
* Values will not be saved to the obj store if the secret is not in-memory and corresponds to a path or env, or if a path or env is set in the `.to()` call. The metadata will be stored in the obj store, and values retrievable through the corresponding path or env variable.
* If `values` is explicitly set to `True` or `False` (default is `None`), then we will correspondingly force saving or not saving the values
=> Update default values behavior for sending secrets to cluster

runhouse/resources/hardware/cluster.py, runhouse/resources/module.py, runhouse/resources/resource.py, runhouse/servers/http/http_client.py, runhouse/servers/obj_store.py, tests/test_resources/test_clusters/test_cluster.py, tests/test_resources/test_modules/test_module.py, tests/test_servers/test_servlet.py
Refactor Module and Cluster so Module methods can be called without Cluster access. test_module passes with MINIMAL, except final sharing test.
Still TODO:
=> Module/Cluster client() contract

runhouse/resources/functions/function.py, runhouse/resources/module.py, runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py, runhouse/servers/servlet.py
- Hack http_server to accept get requests for calling modules so we can call from a browser
- Hack http_server to accept json serialization and query params as inputs
- Change module and function's share to change the visibility of the remote resource
- Change cluster auth to allow calling without a token if module visibility allows
- Change call_module_method in the servlet to only allow unpickling if already authenticated
=> Support unlisted and public visiblity module calls

runhouse/resources/functions/function.py, runhouse/resources/module.py, runhouse/servers/http/http_server.py, tests/test_resources/test_modules/test_functions/test_function.py
- Fix the way we accept query params in the http_server /call methods so serialization doesn't get passed as a kwarg
- Add missing return to module and function .share
- Fix function sharing tests
=> Bugfixes, LOCAL passing

runhouse/main.py, runhouse/resources/blobs/blob.py, runhouse/resources/envs/conda_env.py, runhouse/resources/envs/env.py, runhouse/resources/envs/env_factory.py, runhouse/resources/hardware/cluster.py, runhouse/resources/secrets/provider_secrets/anthropic_secret.py, runhouse/resources/secrets/provider_secrets/aws_secret.py, runhouse/resources/secrets/provider_secrets/azure_secret.py, runhouse/resources/secrets/provider_secrets/gcp_secret.py, runhouse/resources/secrets/provider_secrets/github_secret.py, runhouse/resources/secrets/provider_secrets/huggingface_secret.py, runhouse/resources/secrets/provider_secrets/lambda_secret.py, runhouse/resources/secrets/provider_secrets/provider_secret.py, runhouse/resources/secrets/secret.py, runhouse/rns/login.py, tests/test_resources/test_envs/test_env.py
* add secrets field into env, these secrets are sent to env/cluster alongside env.to or fn.to(env) calls
* add env field to cluster.sync_secrets/add_secrets
* load down env vars into env for login. write down env vars written down through runhouse
* some small bug fixes with paths and loading from name
=> Support secrets in env

runhouse/main.py, runhouse/resources/hardware/cluster.py, runhouse/servers/http/http_client.py, runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py, runhouse/servers/nginx/config.py, tests/test_servers/test_nginx.py
Nginx's proxy buffers were holding back the stream of results before returning them to the client, so this turns it off. Also fixes a few other small bugs.
=> Fix streaming with HTTP/HTTPS/Nginx

tests/README.md, tests/conftest.py, tests/fixtures/local_docker_cluster_fixtures.py, tests/test_obj_store.py, tests/test_resources/test_clusters/test_cluster.py, tests/test_resources/test_clusters/test_pwd_cluster.py, tests/test_resources/test_envs/test_env.py, tests/test_resources/test_modules/test_module.py, tests/test_resources/test_resource.py, tests/test_resources/test_secrets/test_secret.py, tests/test_servers/test_http_server.py, tests/test_servers/test_nginx.py, tests/test_servers/test_servlet.py, tests/test_telemetry.py
Passing locally:
```
pytest -v --level local -k "TestCluster or TestResource"
pytest -v --level local -k "TestEnv"
```
Yet to pass / test:
```
pytest -v --level local -k "TestFunction"
pytest -v --level local -k "TestSecret"
pytest -v --level local -k "TestModule"
pytest -v --level local tests/test_servers/
```
=> Improving cluster fixtures once more to be speedy and cover use cases.

pyproject.toml, pytest.ini, setup.py, tests/requirements.txt, tests/test_servers/test_certs.py
It appears we support 3.11 now that Ray does. Basic testing confirms, but typical constraints stand - we can't cloudpickles functions and send them across Python versions, which we do a couple times in tests (to be fixed shortly).
Also fixes a longtime pesky error wher we were getting a pkg_resources error when attempting to us the CLI without AWSCLI v1 isntalled. For some reason adding a nearly empty pyproject.toml fixes that. Great.
=> Support Python 3.11, fix CLI entrypoint issue

runhouse/resources/module.py, runhouse/servers/http/auth.py, runhouse/servers/http/http_server.py, runhouse/servers/obj_store.py, runhouse/servers/servlet.py
- Auth was only flowing for named resources, corrected so a user with proper cluster access also has access to unnamed resources or non-resources via call_module_method
- Renaming resources in obj_store wasn't actually changing the internal resource.name or rns_address, which was causing auth to use the old rns_address for authentication.
- The call endpoint did not support visibility, now it does
=> Fix two servlet bugs in LOCAL tests

tests/test_resources/test_modules/test_functions/test_function.py
request_headers in defaults.py is still a property, the rns_client one is now
a function.
=> Fix tests on main.

.github/workflows/unit_tests.yaml, runhouse/rns/defaults.py, tests/README.md, tests/conftest.py, tests/fixtures/docker_cluster_fixtures.py, tests/test_obj_store.py, tests/test_resources/test_clusters/test_cluster.py, tests/test_resources/test_clusters/test_pwd_cluster.py, tests/test_resources/test_envs/test_env.py, tests/test_resources/test_modules/test_module.py, tests/test_resources/test_resource.py, tests/test_resources/test_secrets/test_secret.py, tests/test_servers/conftest.py, tests/test_servers/test_http_server.py, tests/test_servers/test_nginx.py, tests/test_servers/test_servlet.py, tests/test_telemetry.py
1. Make `setup_cluster_config` much simpler, just save down a cluster config without sharing anything. Previously, the test_account was creating the cluster and sharing it with Den Tester, which is incorrect because then we were checking if test_account would be blocked from cluster access. Also, in nearly all other logged-in tests, the Den Tester account creates the cluster and shares with Test Account, so the reverse happening here was confusing.
1. Revert the incorrect resource.revoke that was added before.
1. Rename `local_docker_cluster_...` fixtures to `docker_cluster_...`
1. Prevent configs cache from being writen as ~/.rh/config.yaml if empty
1. Skip local/no docker den_auth tests if no token is set.
1. Increase httpx latency timeout for local_client fixture, Den latency spike was …
=> Fix Sharing Behavior of Local Cluster in Unit

runhouse/rns/defaults.py, runhouse/rns/login.py, runhouse/rns/rns_client.py, tests/test_servers/conftest.py, tests/utils.py
1. Allow token and username to be set in RH_TOKEN and RH_USERNAME env vars
2. Fix bug where tokens being set in env vars or directly in python are being written to config file
3. Fix TEST_ACCOUNT token setting behavior to flow through new rh.configs.token flow
=> Introduce proper env-var based token behavior

runhouse/resources/provenance.py, runhouse/rns/defaults.py, runhouse/rns/rns_client.py, runhouse/servers/http/http_server.py, tests/fixtures/docker_cluster_fixtures.py, tests/test_resources/test_clusters/cluster_tests.py, tests/test_resources/test_modules/test_blobs/test_blob.py, tests/test_resources/test_modules/test_folders/test_folder.py, tests/test_resources/test_modules/test_functions/conftest.py, tests/test_resources/test_modules/test_functions/test_aws_lambda/test_lambdas_with_fn.py, tests/test_resources/test_resource_sharing.py, tests/utils.py
After introducing better token getting and setting (including how test_account is set and
supporting RH_TOKEN env vars), this cleans up various token usages which either get
the token directly from the config file (bypassing the locally set token and env var), or
worse, write it directly out to the config file (again, incorrectly).
This also introduces support for finding the .env in the base runhouse package path even
when running tests from a different cwd (which Pycharm does by default).
=> Fix and clean rh.configs.get("token") and similar usages

runhouse/rns/defaults.py, tests/conftest.py, tests/fixtures/docker_cluster_fixtures.py, tests/test_resources/test_modules/test_functions/conftest.py, tests/test_resources/test_modules/test_functions/test_aws_lambda/test_lambdas_with_fn.py, tests/test_resources/test_modules/test_functions/test_function.py, tests/test_resources/test_modules/test_module.py, tests/test_resources/test_resource.py, tests/test_resources/test_resource_sharing.py, tests/test_resources/test_secrets/test_secret.py, tests/test_servers/conftest.py, tests/test_servers/test_http_server.py, tests/test_servers/test_server_obj_store.py, tests/test_servers/test_servlet.py, tests/utils.py
1. Rename test_account to friend_account to clarify that this account should always be
the sharee of resources in tests, not the primary sharer.
2. Add a logged_in_account fixture to make it easy to skip a test if not logged in, and also
ensure that the den_tester account is logged in as needed.
3. Add logged_out context manager for situations where we want to test behavior as if logged out.
=> New account testing fixtures

runhouse/resources/secrets/provider_secrets/provider_secret.py, runhouse/resources/secrets/provider_secrets/sky_secret.py, runhouse/resources/secrets/provider_secrets/ssh_secret.py, runhouse/servers/http/auth.py, tests/test_resources/conftest.py, tests/test_resources/test_envs/conftest.py, tests/test_resources/test_modules/test_module.py, tests/test_resources/test_resource.py
Various tests were becoming flaky due to CI running them in parallel and global Den saving/deleting behavior
colliding. This change gives each test run a unique folder in RNS for a "saved_resource" fixture, which also
cleans up the saved configs after testing completes. It also speeds up tests by not recreating
and deleting resources over and over.
=> Use unique temp resource name when saving to Den in tests

runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/cluster_factory.py
Now that we restart the ray nodes, we can support passing ips. Our tutorials were breaking because ips wasn't supported. Also, we no longer need to rsync runhouse to each node, because rsync sends to all nodes by default, so remove that too.
=> Undeprecate ips argument to cluster

runhouse/resources/functions/function.py, runhouse/resources/hardware/cluster.py
small bug in function's .notebook() following ssh_tunnel return type refactor. also duplicate code with system.notebook() so just use it directly
=> Refactor function notebook

runhouse/resources/hardware/cluster.py, runhouse/servers/env_servlet.py, runhouse/servers/http/http_client.py, runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py, runhouse/servers/obj_store.py, tests/test_servers/test_http_server.py, tests/test_servers/test_servlet.py
Introduce a generic format and precedence for calls into `EnvServlet`.
All functions will take in `data` and `serialization`. They can put whatever
they want in the `data` field and unpack them as tuples before and after, as
done in this PR. This will support pickle and json serialization.
The other parameters to `EnvServlet` functions will be explicit.
The `EnvServlet` should also only call `local` ObjStore functions, and the
ObjStore should deal with all the outside-of-env logic and call the right Env.
=> Overhaul put_resource logic.

runhouse/servers/env_servlet.py, runhouse/servers/http/http_client.py, runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py, runhouse/servers/obj_store.py, tests/test_servers/test_http_server.py, tests/test_servers/test_servlet.py
Change rename_object to new format, turns out for this one we don't even need
to have any logic in the servlet. The obj store abstracts this all away. 
I get rid of the only `put` request and instead make this a `post` to `/rename`
for more consistency.
=> Overhaul `rename_object` logic to new format.

runhouse/servers/env_servlet.py, runhouse/servers/http/http_client.py, runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py, tests/test_servers/test_http_client.py, tests/test_servers/test_http_server.py, tests/test_servers/test_servlet.py
Overhaul `delete_object` logic in similar way to others, no longer calling into
servlet.
=> Overhaul `delete_object` logic.

runhouse/servers/http/http_server.py, runhouse/servers/obj_store.py
Before, obj_store.initialize() would spawn a ray Cluster and start a Cluster
Servlet. Now, it by default only tries to connect to an existing Ray cluster
and get a servlet from there.
Ray and the ClusterServlet are only created upon `runhouse start` or
`HTTPServer()`.
=> Change ray to only be initialized in `runhouse start` or `HTTPServer()`

runhouse/resources/hardware/cluster.py, runhouse/resources/module.py
This allows us to set external=True or False, in case we want a locally-callable
endpoint. Previously if the endpoint was only locally callable, we would only return
None. This is now also consistent with Cluster's endpoint().
=> Change Module's endpoint from propery to function

runhouse/__init__.py, runhouse/resources/asgi.py, runhouse/resources/module.py, tests/test_resources/test_modules/test_server_modules/assets/sample_fastapi_app.py, tests/test_resources/test_modules/test_server_modules/dont_test_server_module.py
Introduces Asgi modulei, including logic for incorporating routes as part of signature,
and asgi factory including logic to find and reload asgi app by pointers.
Successfully calls route endpoint by method directly. Next needs to support calling via requests/curl.
=> Introduce Asgi module and support calling route functions directly

runhouse/servers/env_servlet.py, runhouse/servers/obj_store.py
Return directly if we aren't serializing!
=> Avoid returning `Response` objects via the obj_store when called directly.

runhouse/__init__.py, runhouse/resources/folders/folder.py, runhouse/resources/hardware/__init__.py, runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/utils.py, runhouse/rns/top_level_rns_fns.py, runhouse/servers/cluster_servlet.py, runhouse/servers/http/http_server.py, runhouse/servers/obj_store.py, tests/test_resources/test_clusters/test_cluster.py
Interacting with `rh.here` is important, like the following example
```
import runhouse as rh
rh.here.get(...)
```
This should work in the following cases:
1. `runhouse start` was run locally, and from a different Python process a user runs the code
2. On a cluster that was started remotely via `rh.cluster` or `rh.ondemand_cluster`
Working to include tests for interacting with it as well.
=> Get rh.here to work.

runhouse/servers/http/http_server.py
This allows to filter any metrics e.g. latency by username
=> Create a middleware to propagate the Runhouse username to backend telemetry

runhouse/main.py, runhouse/resources/hardware/cluster.py
With the addition of `nohup` if `screen` is not available, we were
backgrounding by default when running `runhouse start`. Now we should only do
it if `runhouse start --nohup` was passed.
=> Avoid backgrounding by default when doing `runhouse start`.

runhouse/resources/hardware/utils.py
`name` could not be populated if the user is running against a cluster that was
started via `runhouse start`.
=> Make `_current_cluster` return `config` by default instead of `name`.

tests/test_resources/test_envs/conftest.py, tests/test_resources/test_envs/test_env.py
currently local CI env tests only test base_env with no name. add a fixture to local where it does have a name and isn't just the default env. (conda not yet supported on local pending test docker image)
=> Add named env fixture to test in local

runhouse/servers/cluster_servlet.py, runhouse/servers/obj_store.py, tests/test_resources/test_clusters/test_cluster.py, tests/test_servers/test_server_obj_store.py
Support deleting and killing and env servlet through `cluster.delete(["env_key"])`.
Clears the keys existing within the env servlet, removes the env servlet from cluster servlet (and anywhere that keeps track of active env servlets), and kills the corresponding actor.
=> Add deleting env servlet functionality

runhouse/main.py, runhouse/resources/hardware/cluster.py, runhouse/servers/http/http_client.py, runhouse/servers/http/http_server.py, runhouse/servers/obj_store.py, tests/test_resources/test_clusters/test_cluster.py
Rather than call `runhouse status <cluster_name>` in tests and load from RNS
=> Introduce cluster.status()

docker/cuda/Dockerfile, docker/slim/password-file-auth/Dockerfile, docker/slim/public-key-auth/Dockerfile, tests/test_resources/test_resource.py
We were running into an issue where the local_daemon fixture was connecting to the docker cluster ports by default.
=> Don't expose Ray ports in Testing Clusters

runhouse/servers/http/http_client.py, tests/test_servers/conftest.py, tests/test_servers/test_http_client.py, tests/test_servers/test_http_server.py
We should pool tcp connections open to the same cluster, otherwise the mapper
fails with exhausted resources.
=> Speed Up HTTPClient with requests.Session

runhouse/main.py, runhouse/resources/hardware/ray_utils.py, runhouse/rns/top_level_rns_fns.py, runhouse/servers/env_servlet.py, runhouse/servers/http/http_server.py, runhouse/servers/obj_store.py
As @dongreenberg , `runhouse restart` would hang for existing Ray clusters and `runhouse stop` would leave things in a broken state. This does its best to handle this new case.
=> Fix `runhouse restart` to correctly check for exsiting Ray cluster.

runhouse/resources/envs/env.py, runhouse/resources/folders/folder.py, runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/on_demand_cluster.py, runhouse/resources/module.py, runhouse/resources/resource.py, runhouse/resources/secrets/secret.py, runhouse/resources/secrets/utils.py, runhouse/rns/rns_client.py, runhouse/rns/top_level_rns_fns.py, runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py, runhouse/servers/obj_store.py, tests/fixtures/docker_cluster_fixtures.py, tests/test_resources/conftest.py, tests/test_resources/test_clusters/test_cluster.py, tests/test_resources/test_resource.py
Until now we've been setting the _rns_folder of a resource implicitly to
rns_client.current_folder, whether the resource has been saved or not,
so the address is really meaningless. This is a relic from a time when
we tried to save resources constantly as they were created and changed.
Now, it would be much easier to have a reasonable assumption of whether
a resource has been saved and therefore whether its rns_address is
meaningful if passed to another environment. For example, when saving
a resource config as a sub-config of another resource, we need to know
whether we can just save a string because the resource has been saved
or if we need to return the full sub-resource config. This bug in particular
was breaking some things.
This change changes the behavior of `rns_address` to return …
=> Only set rns_address upon save

runhouse/resources/hardware/cluster.py, runhouse/servers/caddy/config.py, runhouse/servers/http/certs.py, tests/test_resources/test_clusters/cluster_tests.py, tests/test_servers/test_caddy.py
Instead of generating separate certs for each cluster, have a single set of certs per user to be re-used across clusters
=> reuse certs across clusters

runhouse/resources/hardware/cluster.py, runhouse/servers/http/http_client.py, runhouse/servers/http/http_server.py, tests/test_servers/test_http_client.py
We were overriding the daemon settings when starting the HTTP server and applying incorrect settings,
and also not using the certs in the HTTPClient to verify requests. This fixes both.
=> Fix Server defaulting and use certs in HTTPClient

runhouse/rns/rns_client.py
We now catch in `handle_exception_response` a `PermissionError` and check if
the text is `No Runhouse Token Provided.` in order to raise the appropriate
HTTPException error. This was not being caught because the log string wasn't
updated, so therefore the error was getting raised on the server and causing
a 500.
=> RNS client error should match the new modified log string.

runhouse/servers/http/http_client.py, tests/test_servers/test_http_client.py
Turns out requests.Session only pools HTTP connections within a session:
https://github.com/psf/requests/issues/3445#issuecomment-263820399
We were creating new connections to the same cluster for no reason. Now we use
a global pool for the process. It would be nice to pool across processes, but
not sure that's straightforward, as requests is barely even threadsafe.
=> Change requests.Session scope to be global

runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/sagemaker/sagemaker_cluster.py, runhouse/resources/hardware/sky_ssh_runner.py, tests/test_telemetry.py
We need to set unique control paths per cluster, and address:ssh_port is
the way we currently distinguish between clusters (including localhost:32322, etc.)
=> Set unique ssh control path per address:ssh_port

runhouse/rns/rns_client.py
We recognize a workdir based on setup.py, pyproject.toml, .git, etc., but we're missing
setup.cfg as a packaging specifier.
=> Recognize workdir based on setup.cfg

runhouse/resources/hardware/cluster_factory.py
When we were trying to load a cluster from den created a new cluster instance instead of loading the existing config from den.
=> cluster from_name bugfix

runhouse/resources/hardware/cluster.py, runhouse/servers/http/http_client.py, runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py, tests/fixtures/docker_cluster_fixtures.py
In [this PR](https://app.graphite.dev/github/pr/run-house/runhouse/434/Only-set-rns_address-upon-save), @dongreenberg sets it up so RNS address is only set on save.
However, we set the cluster name within the cluster servlet remotely once, and then if the RNS address was updated, on_this_cluster would fail since it checked _current_cluster("name") == self.rns_address. So, when RNS address is updated, I now also send a request to the daemon and set the cluster name in the config
=> Fix `name` not being updated in cluster servlet and breaking `on_this_cluster`.

runhouse/servers/http/http_client.py, tests/conftest.py, tests/test_resources/test_modules/test_functions/test_function.py
Previously we had limited coverage of TLS and None connection types.
=> Add tls and HTTP docker fixture to LOCAL tests

runhouse/resources/hardware/cluster.py
`on_this_cluster` was still being computed incorrectly sometimes, when `self.client` was None and therefore `cluster_name` was not actually being updated during `cluster.save()`. in this change, additionally when assigning the client, check if the cluster was saved (has an `rns_address`), and if so, have a call to the update there.
=> Update cluster.save behavior

tests/fixtures/docker_cluster_fixtures.py
@josh is passing the `rns_address` to `HTTPClient` in `connect_server_client`,
and this is not set properly unless the `cluster` is saved. Moving the save
back to unblock.
=> Move `save()` back to before the env installation.

runhouse/resources/hardware/cluster.py, runhouse/resources/module.py, runhouse/servers/env_servlet.py, runhouse/servers/http/http_client.py, runhouse/servers/obj_store.py, tests/test_servers/test_http_client.py
Tuples aren't json serializable. Therefore when we are passing arguments around that could be serialized as json (since we support None, json, pickle), we should have them packed as Lists. When we unpack these, we cast them to tuples and use normal tuple unwrapping methods; this allows us to still check the arguments are in the form we expect.
=> Change all `serialize_data` and `deserialize_data` spots to take lists instead of tuples.

runhouse/servers/http/http_client.py, runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py, tests/test_servers/test_caddy.py, tests/test_servers/test_http_client.py, tests/test_servers/test_http_server.py, tests/test_servers/test_servlet.py
Everywhere we can, use `serialize_data` and `deserialize_data`, especially in tests. This allows us to later parameterize our tests to work with other serialization types (e.g. `json`) and make sure they still work correctly :).
A few spots change the tests to use the response serialization type.
Update the `/cert` method to work correctly.
=> Remove use of `pickle_b64` and `b64_unpickle` directly.

runhouse/servers/http/http_client.py
Bug when doing:
```
import runhouse as rh
sg = rh.fn(name="/dongreenberg/get_stargazers")
for users in sg("run-house/runhouse"):
print(users)
```
=> Fix loading port from endpoint to be `443` or `80` by default.

docs/notebooks/api/clusters.ipynb, docs/tutorials/api/clusters.rst
Add clusters doc page, not listed in the actual webpage yet; waiting for when
we deprecate the `compute` page.
=> Add `clusters` documentation page.

runhouse/resources/hardware/cluster.py, runhouse/servers/http/http_server.py, runhouse/servers/obj_store.py
Right now we're always writing out function call logs, which has a performance implication.
When I ran a server benchmark it introduced a few thousand nearly empty logfiles, even
though I wasn't streaming logs. For now, we can only write them out if stream_logs=True,
as the log info is also available in server.log if needed. When we collect logs in telemetry,
we can write them out then too as needed.
=> Only write out execution logs if we need them

runhouse/servers/env_servlet.py, runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py, runhouse/servers/obj_store.py
We should be disabling telemetry altogether if disable_usage_stats is True and
use_local_telemetry is False. Also, we should be returning bare results if serialization="none",
meaning no Response packaging, just as we do if serialization is None.
=> Disable Telemetry Correctly

runhouse/resources/envs/conda_env.py, runhouse/resources/envs/env.py, runhouse/resources/envs/utils.py, runhouse/resources/packages/package.py, runhouse/utils.py
When calling a method, we use the `StreamTee` in `provenance.py` to log to a file _and_ stdout at the same time, which is how we stream logs from `call`.
However, when we call `env.install`, we call things via subprocess, and these logs aren't propagated. Unfortunately there's no neat way to pipe this (I scoured the entirety of StackOverflow) so we just need to set up a pipe, stream the logs, and print things, and then they'll go to `sys.stdout` and be picked up by the remote log generator. 
While I was here, cleaned up a bit of the conda installation logic.
=> Change some logging to go to `sys.stdout`.

examples/llama2/llama2_ec2.py, examples/stable-diffusion-xl-aws-ec2/sdxl.py, examples/stable-diffusion-xl-aws-inferentia2/inf2_sdxl.py
Notes on relative links (within `www.run.house`):
- Always use a relative path, e.g. `/docs/tuturials...` v. `https://www.run.house/docs/tutorials`
- Remove branch name from urls, that will be automatically handled if needed
=> Update relative links in examples

runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py
* in `get_call`, use the passed in serialization for errors
* in all other spots, respect the serialization that was passed in by the user and return it back in the `Response` object. use this client side in `handle_response` used in http_client
=> Serialize exceptions properly.

runhouse/resources/module.py, setup.py, tests/requirements.txt, tests/test_resources/test_modules/test_module.py
---
<details open="true"><summary>Generated summary (powered by <a href="https://app.graphite.dev">Graphite</a>)</summary>
> ## Description for Pull Request
> 
> ### TL;DR
> Added a method to generate OpenAPI spec for a module, updated dependencies, and added tests for OpenAPI spec generation.
> 
> ### What changed
> - Added a `generate_openapi_spec` method to the `Module` class in `module.py` to generate an OpenAPI spec for the module.
> - Updated dependencies in `setup.py` to include `apispec` and in `tests/requirements.txt` to include `openapi-core`.
> - Added tests in `test_module.py` to test the generation of OpenAPI spec for a module.
> 
> ### How to test
> 1. Ensure the `generate_openapi_spec` method in `module.py` generates the OpenAPI spec correctly for the module.
> 2. Check …
=> Add `generate_openapi_spec` method to `Module`.

runhouse/resources/hardware/cluster.py
When is_shared is called during on-demand cluster initialization, the self.cred_values are an empty dictionary. Therefore, the ssh_private_key is None, and passing it into the Path constructor will raise a ValueError (NoneType).
=> cluster is_shared bugfix

runhouse/resources/module.py, runhouse/servers/http/http_utils.py, tests/test_resources/test_modules/test_functions/test_function.py, tests/test_servers/test_http_server.py
* change `json` to be the default in `CallParams`. this is no big deal because when calling from the `client` we explicitly set serialization to `pickle` anyway
* use `CallParams` to generate the params for our `post_call` method, and set the `data` field to have the explicit params set up by the user
=> Add Runhouse `call` params to openapi spec generation.

runhouse/resources/hardware/cluster.py, runhouse/resources/module.py, runhouse/servers/env_servlet.py, runhouse/servers/http/http_server.py, runhouse/servers/obj_store.py, tests/test_resources/test_modules/test_functions/test_function.py, tests/test_servers/test_http_client.py, tests/test_servers/test_http_server.py
When generating an `openapi_spec` for this code, we need an object / dictionary rather than an arbitrary list... more robust for an actual server to call this now
=> Format serialized_data for `call` as a dictionary with `args` and `kwargs`

runhouse/resources/module.py, tests/test_resources/test_modules/exception_module.py, tests/test_resources/test_modules/test_module.py
ModuleNotFound in module's load_config was previously ignored, for cases when user is loading a (shared) module that doesn't live on their local env. This however also ignores ModuleNotFound errors due to other factors such as missing dependencies, which should be caught.
=> Catching module exception in load_config

runhouse/resources/functionals/mapper.py, tests/test_resources/test_modules/test_functions/test_mapper.py
return error messages in mapper.map output instead of returning None. update retry logic to handle this.
=> Raise exceptions in mapper

runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/on_demand_cluster.py
avoids redundant calls to cluster.is_up()
=> Use check_server instead of is_up for cluster endpoint

runhouse/servers/obj_store.py, tests/conftest.py, tests/test_resources/test_envs/conftest.py, tests/test_resources/test_envs/test_env.py
some confusion about env.name (resource name) vs env.env_name (e.g. conda env's name for passing into runtime_env or for conda commands)
=> Fix env servlet name in put_resource

setup.py
https://linear.app/runhouse/issue/RH-185/pip-install-runhouse[aws]-misses-some-aws-dependencies
=> When installing `runhouse[aws]` install `skypilot[aws]` properly.

runhouse/resources/functionals/mapper.py, runhouse/resources/functions/function_factory.py, runhouse/resources/module.py
previously, specifying system in factory function would send the function/module to the system upon construction. this behavior was updated recently to support constructing a function/module object that already lives on the cluster, such that the object's system attribute was being set but nothing was being sent. however, this is confusing for cases like `rh.function(local_fn, system=remote_cluster)`, as no action is done and the function lives locally.
for clarity, force users to use `.to(system)` for sending function code to a cluster. or `.from_name` or `rh.function(name="name")` for reloading existing function/module that lives remotely.
=> Deprecate system arg from function/module factory functions

runhouse/resources/module.py
doesn't change at all, we can cache it. creds to @dongreenberg for idea for speed up
before:
```
Running 15s test @ http://127.0.0.1:32300/get_pid_basic/call
8 threads and 64 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    81.37ms   38.06ms 322.34ms   83.72%
Req/Sec   103.15     30.77   181.00     74.32%
Latency Distribution
50%   74.02ms
75%   87.99ms
90%  115.63ms
99%  242.10ms
12156 requests in 15.02s, 2.30MB read
Requests/sec:    809.28
Transfer/sec:    156.48KB
```
after:
```
Running 15s test @ http://127.0.0.1:32300/get_pid_basic/call
8 threads and 64 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    55.76ms   22.54ms 226.28ms   89.68%
Req/Sec   146.47     32.04   212.00     76.50%
Latency Distribution
50%   54.53ms
75%   62.44ms
90% …
```
=> Cache `dir(Module)`.

runhouse/resources/module.py
Now that we're caching this, we can get rid of the `rich` variable that we were previously using to speed stuff up. Plus if there's code that calls it with `rich=False`, it would be cached, which isn't what we want.
=> Cache computation of Module's `signature`.

runhouse/resources/functions/function.py
minor improvement.
before
```
Running 15s test @ http://127.0.0.1:32300/get_pid_basic/call
8 threads and 64 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    83.08ms   39.42ms 324.69ms   85.55%
Req/Sec   101.83     29.51   170.00     76.46%
Latency Distribution
50%   75.05ms
75%   86.38ms
90%  118.45ms
99%  273.68ms
11976 requests in 15.09s, 2.26MB read
Requests/sec:    793.70
Transfer/sec:    153.48KB
```
after:
```
Running 15s test @ http://127.0.0.1:32300/get_pid_basic/call
8 threads and 64 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    78.04ms   31.41ms 445.33ms   80.36%
Req/Sec   105.00     22.21   161.00     73.19%
Latency Distribution
50%   72.78ms
75%   81.94ms
90%  110.39ms
99%  204.28ms
12536 requests in 15.07s, 2.37MB read …
```
=> Cache `get_obj_from_pointers` call for function.

runhouse/__init__.py, runhouse/resources/future_module.py, runhouse/rns/top_level_rns_fns.py, runhouse/servers/cluster_servlet.py, runhouse/servers/env_servlet.py, runhouse/servers/http/auth.py, runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py, runhouse/servers/obj_store.py, runhouse/utils.py, tests/test_servers/conftest.py, tests/test_servers/test_server_obj_store.py
`ClusterServlet`, `EnvServlet`, `ObjStore` and `HTTPServer` changed to be async.
Both actors now function as `AsyncActor`s with a single thread (https://docs.ray.io/en/latest/ray-core/actors/async_api.html)
Primarily for performance improvements:
PR below in stack (fn pointer cache):
```
Running 15s test @ http://127.0.0.1:32300/get_pid_basic/call
8 threads and 64 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    59.19ms   13.80ms 128.86ms   83.20%
Req/Sec   135.47     25.44   210.00     74.96%
Latency Distribution
50%   55.58ms
75%   61.70ms
90%   73.78ms
99%  108.33ms
16259 requests in 15.08s, 3.07MB read
Requests/sec:   1078.42
Transfer/sec:    208.52KB
```
to NOW:
```
Running 15s test @ http://127.0.0.1:32300/get_pid_basic/call
8 threads and 64 connections …
```
=> Change daemon-side components to be fully `async` for performance improvements.

runhouse/servers/cluster_servlet.py
to be reflective of if a user uses sky cli command to set autostop instead of cluster.keep_warm/autostop_mins
=> Use sky config for more accurate autostop

runhouse/servers/cluster_servlet.py, runhouse/servers/http/auth.py, runhouse/servers/http/http_server.py, runhouse/servers/obj_store.py, tests/test_servers/test_server_obj_store.py
Killed off all logic where we add a user to the auth cache. Instead, we should function like a true cache and just abstract away the reading with a cache.
Now don't cache all resources, make a new request to Den for every resource + user pairing. Simplified auth calls all around
=> Change `AuthCache` logic to request per user+resource keypair.

runhouse/resources/future_module.py, runhouse/servers/obj_store.py
We want to make sure that heavily synchronous things still run in their own thread since, now that we are using an `AsyncActor`, there is only one thread in the Ray actor.
Useful code dealing with thread pools here:
- https://stackoverflow.com/questions/54758930/python-3-how-to-submit-an-async-function-to-a-threadpool
- https://docs.python.org/3/library/asyncio-eventloop.html#executing-code-in-thread-or-process-pools
If I wanted to run the coroutine in the thread: https://stackoverflow.com/questions/46074841/why-coroutines-cannot-be-used-with-run-in-executor instead of the sync function. Done in this PR: https://github.com/run-house/runhouse/pull/660/files
When to use `run_in_executor`: https://stackoverflow.com/questions/55027940/is-run-in-executor-optimized-for-running-in-a-loop-with-cor …
=> Add `ThreadPoolExecutor` to synchronous function calls server side.

runhouse/constants.py, runhouse/servers/http/http_server.py, runhouse/servers/obj_store.py
This PR decreases the `LOGGING_WAIT_TIME` to .5 from 1 and increases `max_concurrency` from 1000 to 10,000 in both `get_cluster_servlet` and `get_env_servlet` functions at `obj_store.py`.
- The `LOGGING_WAIT_TIME` constant in the `constants.py` file has been decreased to .5 from 1.
- The `max_concurrency` parameter in both `get_cluster_servlet` and `get_env_servlet` functions in the `obj_store.py` file has been increased from 1000 to 10,000.
- The logging of GET call parameters in the `get_call` function in `http_server.py` file has been removed.
This change is made to increase the server's concurrent handling capacity and to make the logging output more efficient by reducing the wait time. It also removes redundant logging.
---
=> Tiny performance improvments

runhouse/servers/http/http_client.py
using a global session is odd here if the settings change, but they shouldn't within a given session... so.. fuck it?
really should figure out if we r ever making too many HTTPClients
=> Remove unused `requests.Session` created in HTTPClient.

runhouse/resources/hardware/cluster.py, runhouse/resources/module.py, runhouse/servers/http/http_client.py, runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py, runhouse/servers/obj_store.py, tests/test_servers/test_http_client.py
We aren't really using the `run_async` arg in object store and HTTP client, with the new async structure. Kill it off!
=> Remove `run_async` argument completely.

pyproject.toml, tests/conftest.py
explained in comments. conflicts with the event loop when it's used in a cluster.
=> Make asyncio event loop session-scoped for tests.

docker/slim/password-file-auth/Dockerfile, docker/slim/public-key-auth/Dockerfile, runhouse/servers/caddy/config.py
Can't install Caddy from Cloudsmith all the time: https://github.com/caddyserver/dist/issues/115.
=> Change Caddy installation to download from Github.

docs/api/python/mapper.rst, runhouse/resources/functionals/mapper.py, tests/test_resources/test_modules/test_functions/test_mapper.py
Previously, we required the user to send their module to the cluster on their own if they wanted to send the mapper to the cluster. This is a stumbling block. We now send the module to the cluster ahead of the mapper, and create the replicas if needed.
=> Handle module.to in Mapper

runhouse/resources/hardware/cluster.py, tests/test_resources/test_clusters/test_cluster.py
Added a breaking test case where we do a bunch of stuff with a passed in cluster.
Originally changed in this PR: https://github.com/run-house/runhouse/pull/477/files
Specifically, when loading a module shared by others, the user may not have permissions to the underlying cluster, so they can't call `set_settings`. 
This was reproduced here: `pytest -v --level release -k "test_shared_readonly"`
=> Remove `set_cluster_name`.

runhouse/resources/hardware/cluster.py, runhouse/resources/module.py, runhouse/servers/http/http_client.py, runhouse/servers/obj_store.py, setup.py, tests/test_resources/test_modules/test_functions/test_function.py, tests/test_resources/test_modules/test_module.py
Adds support for running of any Runhouse module or function `async` server side and client side.
The tests detail this aggressively, but basically you can take any `sync` function, and do `run_async=True` and it will function as `async` locally, e.g.
```
def sync_fn(a, b):
return a + b
fn = rh.function(sync_fn).to(cluster)
sum = await fn(1, 2, run_async=True)
sum = fn(1, 2)
```
the reverse works for `async` functions:
```
async def async_fn(a, b):
return a + b
fn = rh.function(async_fn).to(cluster)
sum = await fn(1, 2)
sum = fn(1, 2, run_async=False)
```
The function will run in a thread on the server if it is sync, and run within the global event loop on the server if it is async.
NOTE: This means that poorly written async functions that run blocking sync things in their code, *will* …
=> Add native async support client side.

runhouse/globals.py, runhouse/resources/hardware/sky_ssh_runner.py
This was a tricky one. Clean up SSH ports / forwarding connections that we use as the program exits. Also, redirect stdin so that terminals that run Runhouse stuff aren't completely borked.
=> Fix SkySSHRunner processes to be correctly cleaned up.

runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py, tests/test_servers/test_servlet.py
Previously, we serialized both the exception and the traceback together, so if the deserialization failed (e.g. if there was a library incompatibility between the client and server which blocked unpickling) we couldn't see the traceback either, even though it's a string. It's important that we try to desrialize the exception so users have a chance to catch it properly locally, but if it's impossible to deserialize, we may as well just raise a runtime error and still print the traceback. If the response from the cluster is still in the old format, we'll still try to unpickle it for compatibility, but we can eventually deprecate that.
=> Don't serialize tracebacks in OutputType.EXCEPTION Responses

runhouse/resources/provenance.py
Because we started running method calls in a threadpool, the output was buffered and only flushed/printed at the end (https://stackoverflow.com/questions/18234469/python-multithreaded-print-statements-delayed-until-all-threads-complete-executi). This changes the StreamTee utility we use to print stdout/logging to flush on each write, per https://mail.python.org/pipermail/tutor/2003-November/026645.html
=> Fix call logging by unbuffering stdout/err in call threadpool

runhouse/servers/http/http_utils.py
Send error along if pickling fails
=> Send the exception_as_str from EnvServlet as well, and use as a fallback if pickling fails.

runhouse/globals.py, runhouse/servers/cluster_servlet.py, runhouse/servers/http/http_server.py, runhouse/servers/obj_store.py, tests/test_servers/test_server_obj_store.py, tests/utils.py
We don't need this to be global, it's only used in the object store. 
In general, minimizing the amount of global stuff we have referencing important objects is better to avoid weird memory issues.
=> Make `env_servlets` cache an instance field instead of global.

runhouse/main.py, runhouse/resources/envs/conda_env.py, runhouse/resources/envs/env.py, runhouse/resources/envs/utils.py, runhouse/resources/functions/aws_lambda.py, runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/cluster_factory.py, runhouse/resources/hardware/on_demand_cluster.py, runhouse/resources/module.py, runhouse/resources/secrets/provider_secrets/provider_secret.py, runhouse/rns/top_level_rns_fns.py, runhouse/servers/http/http_server.py, runhouse/servers/obj_store.py
default env flow
* passed in at cluster initialization
* default env installations is set up on cluster using pure ssh commands
* run the http server start inside the env, passing in default_env which is propagated to the cluster env set up
* put the default env resource on the cluster, and set the env vars after
behavior
* cluster.run, cluster.put, etc runs inside cluster.default_env if not explicitly specified
* if no default env is provided, defaults to base_env
TODOs (can be in follow up?)
* env vars support -- currently set w/ after runhouse start on the default env. can be instead appended to runhouse start command and as a result flow into all subprocesses (flow to add to start cmd kinda annoying tho)
=> Cluster default env

runhouse/resources/envs/env.py, runhouse/resources/hardware/cluster.py, runhouse/resources/module.py, runhouse/resources/secrets/provider_secrets/provider_secret.py, runhouse/resources/secrets/secret.py, tests/conftest.py, tests/fixtures/docker_cluster_fixtures.py, tests/fixtures/on_demand_cluster_fixtures.py, tests/test_resources/test_clusters/test_cluster.py, tests/test_resources/test_clusters/test_cluster_default_env.py, tests/test_resources/test_envs/test_env.py, tests/utils.py
new default_env_cluster test, subclasses test_cluster + some default_env specific testing
fixtures
* new ondemand fixture w/ a default env that's a cluster env
* for existing docker pk ssh fixture, directly set default env=test env instead of sending test env to cluster
=> Add tests for default env

runhouse/resources/module.py
=> Properly raise exception when Module was unable to be loaded from pointers.

runhouse/resources/hardware/cluster.py, runhouse/resources/module.py, tests/test_resources/test_modules/test_module.py
Right now we have `test_shared_readonly` which is the main test that was checking inter cluster calling flows and calling after sharing. This test was being skipped in release testing because `TEST_TOKEN` and `TEST_USERNAME` were not set. 
Now, it fails because the underlying `AsyncGenerator` that we use to mock `async for` calls is not shared with the user. I've renamed this. I've renamed this to `test_share_module_with_generator_read_only_inter_cluster`
Creating a more simple tests that checks `share` and `revoke` with calling a simple Module.
- `export TEST_TOKEN=...`
- `export TEST_USERNAME=...`
- `pytest -v --level local -k "test_share_module_read_only"`
- `pytest -v --level release -k "test_share_module_read_only_inter_cluster"`
- `pytest -v --level local …
=> Rewrite Module tests to be more thorough and separate.

runhouse/main.py, runhouse/resources/hardware/cluster.py
=> Switch `restart_ray` to True so that we start our own Ray cluster instead of using SkyPilot's.

runhouse/resources/envs/env.py, runhouse/resources/envs/utils.py, runhouse/resources/module.py, runhouse/resources/secrets/provider_secrets/provider_secret.py
There are several instances where, if the env happened to be `base_env`, we replace it with the cluster default env. The problem is we don't always replace this client side and it creates some inconsistencies. Wanted to discuss this logic a bit more
I've marked these with `TODO: (default env)`
cc: @carolineechen when you're back
=> Don't replace `base_env` with `system.default_env`.

examples/parallel_embedding/README.md, examples/parallel_embedding/parallel_embedding.py, examples/parallel_embedding/requirements.txt
Fleshed out example using Runhouse primitives to embed URLs in parallel.
=> Parallel embedding model example.

runhouse/servers/cluster_servlet.py
temporarily added sky_utils in #697 to remove sky dependency for autostop, but ended up going w/ approach to just use sky and require sky is installed on ondemand clusters. did not revert references of sky_utils back to original sky usage, fixing in this PR
=> Revert use of sky_utils to skylet configs for autostop

runhouse/resources/hardware/on_demand_cluster.py
_start_ray_workers signature needs to match that of parent
=> Fix multinode start now that we're passing `env`.

examples/parallel-hf-embedding-ec2/README.md, examples/parallel-hf-embedding-ec2/parallel_hf_embedding_ec2.py
**wikipedia, chunk_size=1, 4/4, stream_logs=True**
`Embedded 906 docs across 4 replicas with 4 concurrent calls: 307.0286202430725`
**wikipedia, chunk_size=1, 4/16, stream_logs=True**
`Embedded 906 docs across 4 replicas with 16 concurrent calls: 135.8996410369873`
**wikipedia, chunk_size=1, 4/128, stream_logs=True**
`Embedded 906 docs across 4 replicas with 128 concurrent calls: 115.94204783439636`
**wikipedia, chunk_size=1, 4/128, stream_logs=False**
`Embedded 906 docs across 4 replicas with 128 concurrent calls: 117.65519213676453`
also tested with a larger chunk_size (partitioning) caused an oom
=> Some improvements to the parallel embedding example.

runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/cluster_factory.py
default value `False` for den auth in cluster factory caused alt_options to be set, so calling `cluster("name")` would sometimes result in a config mismatch and fail to reconstruct the resource correctly. set it to none in factory and correspondingly update to False in cluster init instead.
=> Update den auth default to None in cluster factory

runhouse/rns/login.py, runhouse/rns/rns_client.py, runhouse/rns/top_level_rns_fns.py, runhouse/servers/http/http_server.py, runhouse/servers/obj_store.py
remove `save_to` and `load_from` as they're unused. 
simplify try/except/finally blocks
first of a series of rns_client & defaults clean ups
=> Syntactical simplifications, remove unused vars.

runhouse/resources/asgi.py, runhouse/resources/envs/env.py, runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/utils.py, runhouse/rns/top_level_rns_fns.py, runhouse/servers/http/http_server.py, runhouse/servers/obj_store.py, tests/fixtures/docker_cluster_fixtures.py, tests/fixtures/on_demand_cluster_fixtures.py, tests/test_resources/test_clusters/test_cluster.py, tests/test_servers/test_http_client.py
after introducing cluster default envs as a property of a cluster, we no longer need a catch all name for all unnamed envs, which can have confusing behavior. rather,
* cluster w/ a specified default env: if the env is unnamed, the name is assigned to be `{cluster.name}_default_env` (similar to how cluster ssh secrets are automatically named). this is used as the key for the env servlet, and also for purposes of saving the cluster.
* cluster does not have a specified default env: use the var `Cluster.EMPTY_DEFAULT_ENV_NAME = _cluster_default_env`, which is part of the cluster class, rather than the env class. this is used as the env servlet key, and not part of the cluster config so will not be saved.
=> Rename cluster default env name when empty

runhouse/resources/envs/utils.py
fix for https://github.com/run-house/runhouse/pull/761/files#diff-7eae1f3dc70131ce652a773320d1ad2025290d71e6d0df6970cc681d336e85e0L60-L63, may need to refine logic in future or may be less of issue once token flow is finalized
=> Check for default env str in get env from

docs/tutorials/api-envs.rst
https://github.com/run-house/notebooks/pull/13/files
=> Add default env section to envs tutorial

runhouse/resources/module.py
If a user runs cluster.run(["pip install ...."]) after the env process is already created, we need to refresh the sys.path inside the env process to incorporate any new directories added.
=> Refresh sys.path upon loading a new module

runhouse/main.py
=> Make sure that the `--help` message isn't printed on normal `runhouse` commands.

runhouse/resources/envs/env.py, tests/test_resources/test_envs/test_env.py
In [this commit](https://github.com/run-house/runhouse/commit/63a520f6dc7a1d81fd4994ddf309ffe8164431f1#diff-b592e248986d5900342d41f0f6edc4a51527b0aa247c5bae9c24aef9dba58c45L183) we started sending all provider secrets to the env they were a part of, rather than to the base/default env. 
This requires that they are sent after the env servlet is created. This is broken in latest release (0.0.28).
=> Fix env installations that contain a provider secret.

runhouse/main.py, runhouse/resources/envs/utils.py, runhouse/resources/hardware/cluster.py, runhouse/resources/packages/package.py, runhouse/servers/http/http_server.py
note that runhouse start/restart should be called from inside the working dir on the cluster to properly install those requirements
=> Support default env syncing for runhouse start/restart

runhouse/resources/hardware/cluster.py
When we pass basic auth, this gets used as the `Authorization` header. 
We don't actually need this for anything... the `ssh_user` and `password` should only be needed to create the `ssh_tunnel`, so let's just not send this at all.
=> Don't pass basic auth to password cluster HTTP calls.

pyproject.toml, requirements.txt, setup.py
See issue: https://github.com/aws-neuron/aws-neuron-sdk/issues/893.
=> Newer setuptools version breaking import from `pkg_resources`.

runhouse/servers/cluster_servlet.py
When the cluster is inited for the first time, when we check config.token we get false, because the config.yaml is set after the cluster servlet is up. 
Therefore this check is preventing from the schedulers to run, and we were forced to restart the server.
The config.yaml should be set properly later, so if there will be a problem with the config.token, the cluster schedulers will raise an error.
=> Fix cluster schedulers setup

runhouse/constants.py, runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/on_demand_cluster.py, runhouse/rns/rns_client.py
Add test to check status ping to den schedluer logic (#862)
Co-authored-by: Alexandra Belousov <sashabelousovrh@Alexandras-MacBook-Pro.local>
move config.yaml creation to restart_server
=> Fix cluster status scheduler, move config.yaml creation to restart server()

runhouse/main.py, runhouse/rns/login.py
updates to secrets login
* by default no prompt to upload/download secrets. use `--sync-secrets` flag to get those prompts
* if no secrets found in vault, don't prompt to download
* fix for secret loading/conversion
=> Update secrets login flow

docs/tutorials/quick-start-den.rst, examples/langchain-rag-ec2/README.md, examples/langchain-rag-ec2/langchain_rag.py, examples/llama2-13b-ec2/llama2_ec2.py, examples/llama2-fine-tuning-with-lora/llama2_fine_tuning.py, examples/llama2-with-tgi-aws-inferentia2/tgi_llama2_inferentia.py, examples/llama2-with-tgi-ec2/tgi_llama_ec2.py, examples/llama3-8b-ec2/llama3_ec2.py, examples/mistral-aws-inferentia2/mistral_inferentia.py, examples/mistral-with-tgi-ec2/tgi_mistral_ec2.py, examples/parallel-hf-embedding-ec2/parallel_hf_embedding_ec2.py, examples/stable-diffusion-xl-aws-inferentia2/inf2_sdxl.py, examples/stable-diffusion-xl-ec2/sdxl.py
Walked through the Llama 3 example and the Den Quick Start and caught a few things, notably:
- Missing python for conda setup
- Showing explicit pip install packages, in case you are on /examples and not in the repo
- Typos in model names
- Removed some empty code blocks on Den Quick Start + fixed an incorrect function variable name
=> Clarify setup in docs and den quick start

runhouse/rns/login.py, tests/test_resources/test_secrets/test_secret.py
added for backwards compatibility 6 months ago. secrets should already be converted to resources by now for any semi active user
=> Remove resource conversion check for secrets

examples/llama2-fine-tuning-with-lora/llama2_fine_tuning.py
Noticed an extra `"```"` causing the fine tuning example to render incorrectly. Quick fix.
=> Fix bug in starting example code block

runhouse/resources/module.py
This makes runhouse work in [marimo notebooks](https://github.com/marimo-team/marimo), in addition to Jupyter notebooks.
=> improvement: add support for running in a marimo notebook

runhouse/main.py, runhouse/resources/packages/package.py, runhouse/rns/defaults.py
default env introduced non-expanded system objects to avoid infinitely recursive subconfigs. handle this when calling package.to()
=> Handle string system in package .to

runhouse/rns/defaults.py, tests/fixtures/on_demand_cluster_fixtures.py, tests/test_resources/test_clusters/test_on_demand_cluster.py, tests/test_resources/test_data/test_package.py
plus docker cluster specific tests
=> Add docker test fixture

examples/langchain-rag-ec2/langchain_rag.py, examples/llama3-vllm-gcp/llama3_vllm_gcp.py, examples/parallel-hf-embedding-ec2/parallel_hf_embedding_ec2.py, examples/parallel-hf-embedding-ec2/requirements.txt
Noticed some errors being reported for missing modules, likely from some missing/incorrect `pip install` scripts in the examples
=> Fix imports in examples

runhouse/resources/module.py, tests/test_resources/test_envs/test_env.py
Breaking example, where we initialize `reqs` in the constructor, which gets set in the env, but is not propagated in `.to` because the env has no name. Pretty sure we can just send `self.env` and later we have a check if it has no name to take a different path.
See test for repro.
=> Propagate `self.env` if it was set.

runhouse/resources/envs/utils.py, runhouse/resources/folders/folder.py, runhouse/resources/hardware/cluster.py, runhouse/resources/module.py, runhouse/resources/packages/package.py, runhouse/rns/rns_client.py, runhouse/utils.py, tests/test_den/test_rns.py
* Enabled unit test for search
* Moved these search functions out of `RNSClient` into normal helpers
* Changed to first breadth first for normal things indicating "projects" and then for the `rh` directory, which could be put... kind of anywhere. We should probably rid ourselves of depending on this.
=> [breaking] Change `locate_working_dir` to be breadth-first.

runhouse/resources/folders/folder.py
just making this more readable, it was bothering me.
=> [minor] simplify Folder path logic.

runhouse/resources/secrets/provider_secrets/ssh_secret.py
Handling secret syncing more gracefully to resolve this error from running `runhouse login`
```
Retrieve your token 🔑 here to use 🏃 🏠 Runhouse for secrets and artifact management: https://run.house/account#token
Token: 
Download your Runhouse config to your local .rh folder? [Y/n]: y
Download secrets from Vault to your local Runhouse environment? [y/N]: y
Upload your local .rh config to Runhouse? [y/N]: y
Upload your local enabled provider secrets to Vault? [y/N]: y
INFO | 2024-06-07 16:13:03.070479 | Loaded Runhouse config from /Users/matthewkandler/.rh/config.yaml
yINFO | 2024-06-07 16:13:03.655838 | Saving config for ssh-sky-key to Den
INFO | 2024-06-07 16:13:03.784929 | Saving secrets for ssh-sky-key to Vault
INFO | 2024-06-07 16:13:04.464916 | Loading down secrets for ssh-sky-key …
```
=> Handle login error missing private_key key

runhouse/resources/envs/env_factory.py, runhouse/resources/envs/utils.py, runhouse/resources/functions/aws_lambda.py, runhouse/resources/functions/function_factory.py, runhouse/resources/hardware/cluster.py, runhouse/resources/module.py, runhouse/servers/http/http_server.py, tests/test_resources/test_clusters/test_cluster.py, tests/test_resources/test_envs/test_env.py
If you pass working_dir as ./, it'll still work and run the detection algorithm. However, omit it by default, as when the module or function is actually sent to the env, then the working_dir is automatically added based on the file where the code was.
=> Remove defaulting `working_dir` to `./`.

runhouse/resources/hardware/cluster.py
don't really need the `self.on_this_cluster()` section anymore.
to me it looks like -- `default_env` will always be set to something, and so we'll use `self.call` for all the `on_this_cluster` stuff, which will branch in there on its own.
=> Restructure `cluster.run` to be more clear.

runhouse/resources/hardware/cluster.py
Not sure why we need this. Maybe I should just deprecate it.. but very very much doubt anyone is using it.
=> Remove `port_forward` arg in `cluster.run`.

runhouse/resources/functions/aws_lambda_factory.py, runhouse/resources/functions/function_factory.py, runhouse/resources/module.py
Only change the module pointers to the `remote_import_path` when actually running `.to`. 
In that case, we generate the `remote_import_path` relative to whatever env it is being `.to` into.
=> Change `pointers` to store absolute path and work with `.to`.

examples/llama2-13b-ec2/llama2_ec2.py, examples/llama2-fine-tuning-with-lora/llama2_fine_tuning.py, examples/llama3-8b-ec2/llama3_ec2.py, examples/llama3-fine-tuning-lora/llama3_fine_tuning.py, examples/llama3-vllm-gcp/llama3_vllm_gcp.py
check_server no longer automatically ups a cluster if it is down (but will raise an error instead). upping and checking that a cluster is up should be something the user should handle themselves
=> Add up_if_not to clusters in examples

docs/installation.rst
Fixes the formatting of the links in `/docs/installation.rst` - they were missing the trailing `_`
The final code block isn't rendering in docs either, tried adding an extra line to see if that helps.
=> Fix install docs links

runhouse/main.py, runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/on_demand_cluster.py, runhouse/resources/hardware/utils.py
when loading on demand cluster from name (Den), if different IPs are found in the local sky db (refresh=False), then update the IPs. the local IPs should be more recent than the saved IPs
note: it is possible the cluster was autodowned but still in the local db, in this case the local IPs will still be used but won't work (calling up_if_not or _ping will correct this, but this is to avoid calling refresh in the constructor). 
note: we do not resave the cluster either
=> Check ips for ondemand clusters when loading from Den

runhouse/resources/hardware/cluster.py, tests/fixtures/docker_cluster_fixtures.py
Logic is now as follows.
`resync_rh` is `None` by default. In this case or if `resync_rh` is just set to `True`:
- If Runhouse is not installed on the remote cluster OR if Runhouse is installed editable locally
- Then we first install the identical Ray version to local, then install either the local Runhouse or the matching version
If `resync_rh` is False, then we for sure do not sync Runhouse in any way.
=> Change `resync_rh` to None by default and match Ray version.

runhouse/resources/hardware/cluster.py
Switching this back because conda envs need to be created before we can do `conda run` commands, and then the `self.run` commands fail and Runhouse doesn't get installed in the conda env. 
Will think of a better fix later.
=> Switch `default_env` sync to be before installling Runhouse.

docker/slim/public-key-auth-conda/Dockerfile, tests/fixtures/docker_cluster_fixtures.py
Add a new dockerfile with miniconda installed to be able to test conda default_env in a local docker cluster. Unfortunately changing the dockerfile to use the miniconda base image did not work for the other local clusters which don't use conda default env, not for lack of trying. Ideally we can consolidate these somehow soon.
=> conda_env in local Docker cluster

.github/workflows/nightly_release_testing.yaml, .github/workflows/setup_release_testing/action.yaml
We should be able to assume the `oss-role` for authenticating with the cluster and running the tests, but reverting until that's sorted
=> unblock k8s test in CI

runhouse/resources/hardware/cluster.py
move `check_server` into the client construction to avoid extra calls when making every client call. also remove `restart_server` when there are connection errors, as this wipes the entire runhouse state on the cluster. instead, reset and try to reconnect the client and throw an error if that still doesn't work.
=> Update cluster client flow

runhouse/resources/folders/folder.py, runhouse/resources/module.py, runhouse/servers/http/http_client.py, runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py, tests/fixtures/folder_fixtures.py, tests/test_resources/test_clusters/test_cluster.py, tests/test_resources/test_data/test_folder.py, tests/test_servers/test_http_server.py
* serializing folder contents where appropriate before sending them over the wire with http_client.put()
* fixing Folder ls call when calling via HTTP
* revert Folder to inherit as a resource for now
* revert docker folder fixture to no longer be associated with test org
* Get CI fully passing
=> folder as resource fixes

runhouse/resources/blobs/blob.py, runhouse/resources/blobs/file.py, runhouse/resources/hardware/sagemaker/sagemaker_cluster.py, runhouse/resources/module.py, runhouse/resources/secrets/secret.py, runhouse/rns/utils/names.py, runhouse/servers/http/http_server.py, runhouse/servers/obj_store.py, runhouse/utils.py
Since this doesn't rely on any Runhouse utilities, we can move it to the generic utils file and use it more easily.
=> Move `_generate_default_name` into general utilities.

runhouse/servers/cluster_servlet.py
Sometimes clusters do not generate logs between two consecutive cluster checks. Therefore, no logs were sent to Den, and we were logging the following info message: 'There were no logs to send to Den'. In the next cluster check run, we spotted that a new log line was generated ('There were no logs to send to Den'), and it was sent to Den. This is the reason the following log preview was displayed in the UI:
(Notice that every two log lines are sent in 2 minutes apart, which makes sense) 
This is a bit odd and unintuitive, therefore I made 2 changes to the way we are logging that 'no logs were sent to Den':
1.   I updated the log message to be more precise: "No logs were generated in the past {interval_size} minute(s), logs were not sent to Den."
2. We are logging this message in debug …
=> log 'no logs were sent to den' as debug

runhouse/rns/rns_client.py, runhouse/servers/cluster_servlet.py, tests/test_resources/test_clusters/test_cluster.py
cluster CI tests are expected to fail. Once we'll deploy the relevant version to den-prod, the tests will pass. (There is a stuck with den changes as well.)
=> Server cpu memory info display only relevant info

runhouse/servers/http/http_server.py
We're not setting a `run_name` on the `get_call` endpoint. This comes up when [calling a function via CURL](https://github.com/run-house/runhouse/actions/runs/10487756209/job/29048800796).
This update creates a run name if not provided in the request
=> create `run_name` for `get_call` http route if not specified

runhouse/resources/module.py, runhouse/servers/obj_store.py
=> Improve the env defaulting logic for a module to use the env that it was created in.

requirements.txt, runhouse/resources/module.py, runhouse/servers/http/http_client.py, runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py, runhouse/servers/obj_store.py, setup.py, tests/test_servers/test_caddy.py, tests/test_servers/test_http_server.py
Some pydantic docs for reference: 
https://docs.pydantic.dev/2.8/migration/#validator-and-root_validator-are-deprecated
https://docs.pydantic.dev/latest/concepts/fields/#field-representation
Currently, we still using the pydantic.v1 validator, because Ray is installing pydantic < 1.10.0 (https://github.com/ray-project/ray/blob/master/release/requirements.txt). Not sure for how long we could use it thought: according to pydantic documentation looks like v1 deprecated methods will be completely deprecated after v3 is released. (https://docs.pydantic.dev/latest/version-policy/#pydantic-v2). So probably need to talk to ray about their plan (if such exists) to upgrade pydantic v1 to v2.
=> upgrade ray + pydantic versions

runhouse/main.py, runhouse/resources/envs/env.py, runhouse/resources/envs/utils.py, runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/kubernetes/rsync_helper.sh, runhouse/resources/hardware/on_demand_cluster.py, runhouse/resources/hardware/sagemaker/sagemaker_cluster.py, runhouse/resources/hardware/sky_ssh_runner.py, runhouse/resources/hardware/ssh_tunnel.py, runhouse/resources/hardware/utils.py, tests/test_resources/test_clusters/test_on_demand_cluster.py
=> Integrate k8s command runner into cluster

requirements.txt, runhouse/constants.py, runhouse/main.py, runhouse/servers/cluster_servlet.py, runhouse/servers/env_servlet.py, runhouse/utils.py, setup.py, tests/test_resources/test_clusters/test_cluster.py
Updated a bit the runhouse status cli cmd output, now that we get CPU and GPU util properly:
* We are printing GPU utilization% only on the server level, because we can't calculate it on the env level
* We are printing the CPU utilization% on the server level as well, not just on the env level.
=> Add intervals to gpu and cpu util calcs

runhouse/main.py, tests/test_resources/test_clusters/test_cluster.py
Output will looks as follows:
**Single-node GPU**
**Multi-node GPU**
**Single-node CPU**
**Multi-node CPU**
=> print cloud info in cluster status

runhouse/main.py, tests/test_resources/test_clusters/test_cluster.py
=> status cli prints active funtions info

runhouse/resources/hardware/on_demand_cluster.py
to add to launched_properties, but not directly from sky - memory, os
=> Add more sky resource properties to cluster launched properties

tests/test_resources/test_clusters/test_on_demand_cluster.py
test fails and then causes several future tests to fail. may not be mocked properly and causing cluster state to be affected during the teardown call. skip for now for more accurate nightly release tests
cc @BelSasha
=> Skip status teardown test for now

runhouse/main.py, runhouse/resources/hardware/cluster.py, runhouse/rns/rns_client.py, runhouse/servers/cluster_servlet.py, runhouse/servers/http/auth.py, runhouse/servers/http/http_client.py, runhouse/servers/obj_store.py, tests/test_resources/test_clusters/test_cluster.py, tests/test_resources/test_resource_sharing.py, tests/test_servers/test_http_client.py, tests/test_servers/test_http_server.py
- generate cluster tokens in Den instead of client side. tokens are now OIDC compliant, and required for enabling telemetry
- prevent regenerating the cluster tokens unnecessarily on the client side
- ping new den API on clusters in order to validate the token received
=> load cluster token from Den instead of generating client side

.github/workflows/local_tests_den_dev.yaml, tests/test_login.py, tests/utils.py
Update env vars for the various den accounts used in testing
=> updated tokens for dev ci testing

.github/workflows/release_precheck.yaml
Our current Ray version is no longer supported for python 3.7 (https://github.com/ray-project/ray/issues/39395)
=> update release pre-check and drop py3.7 support

runhouse/servers/cluster_servlet.py, tests/test_resources/test_clusters/test_on_demand_cluster.py
* don't permanently break out of the while loop when initial conditions arent met (interval size could potentially be adjusted)
* remove redundant checks
* update autostop at beginning of loop (may be better split out of the status loop in the future)
=> Update autostop loop

runhouse/main.py
=> By default, cluster list prints only running clusters

runhouse/resources/secrets/provider_secrets/api_key_secret.py, runhouse/resources/secrets/provider_secrets/aws_secret.py, runhouse/resources/secrets/provider_secrets/azure_secret.py, runhouse/resources/secrets/provider_secrets/gcp_secret.py, runhouse/resources/secrets/provider_secrets/github_secret.py, runhouse/resources/secrets/provider_secrets/huggingface_secret.py, runhouse/resources/secrets/provider_secrets/lambda_secret.py, runhouse/resources/secrets/provider_secrets/provider_secret.py, runhouse/resources/secrets/provider_secrets/ssh_secret.py
Needed for the new [launcher service](https://github.com/run-house/runhouse-launcher), where we use the secrets APIs to save down SSH keys in a temp env/directory for the user. In this case we don't need to persist the config value in the RH config, so adding an option to skip. Shouldn't disrupt any existing OSS APIs
=> add option to skip writing secret down to rh config

runhouse/resources/packages/package.py
=> Allow `.to` on packages without an `InstallTarget`, just make it a no op.

runhouse/resources/packages/package.py
=> Package `_install` doesn't need to `rsync` because `.to` will always happen first to all nodes.

runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/on_demand_cluster.py, runhouse/resources/hardware/utils.py, runhouse/resources/secrets/provider_secrets/ssh_secret.py
perform some extra setup to allow for using your own default creds for ondemand clusters.
* if ~/.ssh/sky-key exists: do nothing, sky will launch with those creds
* if ~/.ssh/sky-key does not exist and default_ssh_key exists, copy those creds to ~/.ssh/sky-key so sky can launch with those creds
* if neither exists, do nothing. sky will create the creds when it launches
note that this does not support passing in custom `ssh_creds` for ondemand_clusters. it's only for the case of defaulting the sky-key to your default key if you have a default key but no sky key.
=> Add support for ondemand cluster default creds

runhouse/resources/hardware/utils.py, runhouse/resources/packages/package.py, runhouse/servers/cluster_servlet.py, runhouse/servers/servlet.py
nvcc might not be installed by default (e.g. minimal updated sky images) -- use `/usr/local/bin/cuda/nvcc` as fallback and update code to skip the cuda version detection code if unnecessary
=> Update cuda detection

runhouse/resources/hardware/on_demand_cluster.py
Sky status may not be reachable for cluster launched with Den, so fallback to using IPs set directly on the cluster when restarting Ray
=> Fix restart_ray for den launched clusters

runhouse/resources/hardware/utils.py
=> Fix list typing

runhouse/resources/distributed/dask_distributed.py, runhouse/resources/future_module.py, runhouse/resources/module.py, tests/test_resources/test_modules/test_module.py
This looks like a quick change but is acutally a big deal. It enables serialization and deserialization of Modules objects across dramatically different Python environments. The `__reduce__` method ensures Module subclasses are pickled as base Module objects, preventing deserialization errors when pickle attempts to locate the Module subclasses in remote environments.
=> Fix Module serialization across disperate python versions

runhouse/cli_utils.py, runhouse/resources/hardware/utils.py
Before we displayed the Last Active as unknown: 
With the introduced change we just display the Last Active as None (empty): 
Cluster.list() pythonic output:
=> cluster list: display unknown last_active_time as None

runhouse/resources/hardware/launcher_utils.py
Fixes an issue where the SSH creds on the cluster locally weren't matching up with the sky secret assigned by the launcher
=> Set sky secret on den clusters

runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/launcher_utils.py, runhouse/resources/hardware/on_demand_cluster.py, runhouse/servers/obj_store.py, runhouse/servers/servlet.py, tests/test_resources/test_clusters/test_cluster.py, tests/test_resources/test_resource.py
replace `self.internal_external_ips` with just `self.internal_ips` (`self.ips` already stores external ips). leave ability to load internal_external_ips from kwargs for backwards compatibility for now.
=> Replace cluster internal_external_ips attribute with internal_ips

runhouse/resources/hardware/cluster_factory.py, runhouse/resources/hardware/on_demand_cluster.py
Required for setting context and/or namespace remotely for the den launcher
=> persist k8s namespace and context in ondemand cluster config

runhouse/resources/hardware/launcher_utils.py, runhouse/resources/secrets/secret_factory.py
- Use the established SSH creds for cluster teardown
- Ensures secrets are saved to user's folder instead of `default_folder` (relevant for organizations)
=> Keep secrets in user namespace, fix creds on den teardown

runhouse/resources/resource.py
Originally I was going to update the `def rns_client` method to use the `rns_client.current_folder` when `_rns_folder` is missing but I think this is more acutely solving the issue I was having.
Case:
- Define an `env` with a name without a folder
- Define a cluster with `default_env=env`
- Save
- When re-running the script, env wasn't recognized because the `_compare_config_with_alt_options` method looks at `rns_address` which is None for a newly defined env (without loading or saving to Den)
The `current_folder` solution could fail in a case where you define a cluster name as `/<ORG_NAME>/gpu` since the current folder would NOT match the folder applied to the env after saving (which would be the save as the cluster, `<ORG_NAME>`...
Maybe this is not a problem in a post-image world
=> Compare resources in config without rns_address

runhouse/resources/hardware/on_demand_cluster.py
Teardown the cluster itself before updating Den. Two main reasons for this: 
- if there's an exception with the teardown proper we shouldn't update the DB 
- previously we were only updating the status of the runhouse daemon, but now we also update the status of the cluster itself. doing so means that if we update the DB first, the teardown will fail bc the cluster is marked as already "stopped"
=> reorder teardown sequence

runhouse/resources/hardware/cluster_factory.py
passing in `image=xxx` into rh.cluster() not actually propagating right now
=> Add image arg to cluster factory

runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/sky/command_runner.py, runhouse/resources/hardware/sky_command_runner.py, runhouse/servers/cluster_servlet.py
Context: the config yaml needs to be on the cluster before we run the restart command, otherwise cluster servlet checks (damon activity, logs, etc.) will fail initially 
Potential options to discuss: 
- revert back to rsyncing instead of requiring an HTTP connection 
- decouple cluster servlet initialization from the server restart 
- polling / waiting mechanism where cluster servelt initialization only starts once the config has been sent to the cluster
- passing in config as server restart params 
**Dec 2nd**:
After talking to @carolineechen and @rohinb2, decided to revert back to rsyncing instead of requiring an HTTP connection (reverting PR #[1478](https://github.com/run-house/runhouse/pull/1478) ).
=> Update cluster restart server so periodic cluster status checks won't fail

MANIFEST.in
In the launcher we were failing to rsync with the cluster, bc the bash script was missing 
```
ERROR | 2024-12-04 08:01:21 | [sky_handler.py:handle_exception:324] | Command chmod +x /usr/local/lib/python3.9/site-packages/runhouse/resources/hardware/kubernetes/rsync_helper.sh &&  rsync -Pavz --ignore-existing --filter='dir-merge,- .gitignore' -e /usr/local/lib/python3.9/site-packages/runhouse/resources/hardware/kubernetes/rsync_helper.sh '/tmp/tmpgoc4d6ws/config.yaml' poppy-k8s-eks-cpu-4-cd9f-head@default:'/home/sky/.rh/' failed with return code 1.
root@launcher-app-5c87f894b9-v9hfm:/tmp/tmpgoc4d6ws# chmod +x /usr/local/lib/python3.9/site-packages/runhouse/resources/hardware/kubernetes/rsync_helper.sh &&  rsync -Pavz --ignore-existing --filter='dir-merge,- .gitignore' -e …
```
=> ensure k8s rsync helper is included in installed package

runhouse/cli_utils.py, runhouse/resources/hardware/utils.py
This PR includes some changes that unblocks cluster CI tests.
Later on should add fixes / changes to:
1. cluster status cli output, now that we have processes instead of envs
2. cluster list cli output, now that we have daemon status and cluster status separated
But those should be in separate PRs, since those are more "fundamental" changes.
=> fix cluster CI tests

docs/api/python/secrets.rst, runhouse/resources/secrets/provider_secrets/docker_secret.py, runhouse/resources/secrets/provider_secrets/providers.py
Values for storing and mapping env vars necessary to load docker images from private registry or ecr. 
- `rh.provider_secret("docker")` will extract values from `SKYPILOT_DOCKER_USERNAME/PASSWORD/SERVER` env vars
- can also create a dict mapping "username" "password" "server" to values and pass that in to `rh.provider_secret(provider="docker", values=values)`
- `_map_env_vars` implemented in later PR can be used to get mapping of sky env var to value
=> Add DockerRegistrySecret

runhouse/resources/hardware/cluster.py
I don't think we can run the server stop command through http, since server gets killed midway and we don't get the status back.
=> Fix server stop for remote cluster

tests/fixtures/resource_fixtures.py, tests/test_resources/test_clusters/test_cluster.py
Fixing the `cluster list all pythonic test`, issue was found after we started running den clean up cron every midnight.
=> fix cluster list all pythonic test

runhouse/cli_utils.py, runhouse/main.py, runhouse/resources/hardware/cluster.py
* we can't call `_is_server_up` for `rh.here` since we can't call/create a client or check is_up from on the cluster. instead, checking if an obj store error or connection error is being thrown to detect if server is down, unless there's a better approach for on the cluster (rh.here)
* if server is down, we log and ask the user to run `runhouse cluster status` but that itself will fail if the server is down? or is that not supposed to be the case?
=> Fix server status

runhouse/resources/hardware/cluster.py
run_bash_over_ssh is synonymous with old run bash right?
=> One Tiny Swap

runhouse/constants.py, runhouse/resources/hardware/launcher_utils.py, tests/fixtures/on_demand_cluster_fixtures.py, tests/fixtures/static_cluster_fixtures.py
The problem:
`ssh-sky-key` is not being deleted during den clean up (which makes sense, it should not have). Therefore, there might be a mismatch between the `ssh-sky-key` values saved as a den secret, and the local` ssh-sky-key` values. (For example the `ssh-sky-key` values saved in den might belong to user A who created and saved this secret for `den_tester` and the local values might belong to user B who is running release testing with `den_tester`). This is the explanation to the following issue I was seeing:
```
ERROR tests/test_resources/test_modules/test_module.py::TestModule::test_module_from_factory[static_cpu_pwd_cluster_den_launcher] - ConnectionError: Could not reach testing-b83cbcb4-14fb-4c7b-ae13-7c73b62b8d2c-20241211-173742-den-aws-cpu-password 44.204.57.6. Is cluster up? …
```
=> fix sky key secret creation so it won't break release testing locally

tests/conftest.py, tests/fixtures/static_cluster_fixtures.py, tests/test_resources/test_modules/test_module.py
Change module tests to run on a den-launched cluster when test level is set to `release`.
=> update module tests to use den-launched cluster

runhouse/resources/hardware/cluster.py
prevent docker secret from being written out in echo; not necessary to store on the cluster
=> Exclude image id and docker secret from json on cluster

runhouse/resources/distributed/pytorch_distributed.py, runhouse/resources/distributed/supervisor.py, runhouse/resources/module.py
* use `ensure_process_created` instead of `create_process` for replicas - now can rerun distributed scripts
* remove `timeout` from pytorch distributed forward - was not being used + caused issue with unnamed args in forward (`train_ddp(10)` in basic distributed was passing in the 10 to the `timeout` arg and reporting that `epochs` arg was missing)
=> Fix some distributed bugs

.github/workflows/nightly_release_testing.yaml, tests/test_resources/test_clusters/test_cluster.py
For some reason, when running the cluster list tests as part of the whole test suite in CI env, they fail (when running them locally they pass, with no consistency issues). Splitting the cluster list tests of static & k8 clusters solved the issues I was seeing.
=> Nightly release run cluster list test separately for k8 and static clusters

docs/tutorials/api-clusters.rst, runhouse/resources/hardware/cluster_factory.py
`default_vpc` is a little tricky to handle across various cloud providers. so for now removing it until we get more feedback on how that support should look
=> simplify custom vpc setting

runhouse/resources/hardware/on_demand_cluster.py, tests/fixtures/on_demand_cluster_fixtures.py, tests/test_resources/test_clusters/test_on_demand_cluster.py
Tests that are still fails:
1. `test_autostop_call_updated` - both in CI and locally
2. `test_autostop_function_running` - both in CI and locally. 
Need further investigation, based on Q1 priorities.
=> Fix k8 nightly release tests failures

runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/on_demand_cluster.py
relevant for launching where we provision separately from starting the server daemon
=> don't check if server is up when using `start_server`

.github/workflows/setup_release_testing/action.yaml
skypilot supports only up to [python 3.11](https://docs.skypilot.co/en/latest/getting-started/installation.html), so we need to verify that the nightly release tests are using the supported python version.
=> fix nightly release tests setup

runhouse/cli_utils.py, runhouse/main.py
@jlewitt1 Decided to leave out printing the launcher type in `rh cluster status` for now, since our go-to is to launch clusters primarily using Den.
=> cli commands improvements

tests/test_resources/test_clusters/test_cluster.py
Motivation: we changed the` cluster.list()` default behavior to return all clusters *owned* by the user; even if a cluster is saved in an org, it will be returned as part of the `cluster.list()` output. Therefore, we don't need in using the friend account in the cluster list tests anymore.
=> minor refactor to cluster list tests

runhouse/resources/hardware/utils.py
causing `test_condensed_config` to fail in release tests
=> Don't update compute properties in print

runhouse/resources/hardware/launcher_utils.py
Cleanup of the params sent to the Launcher for teardown. Pending an update to Den to remove `ssh_creds` as required and instead infer them from the resource itself.
=> Removes redundant ssh_creds from teardown

docs/api/python/image.rst, runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/utils.py, runhouse/resources/images/builtin_images.py, runhouse/resources/images/image.py, runhouse/resources/packages/package.py, runhouse/servers/obj_store.py, tests/fixtures/docker_cluster_fixtures.py, tests/fixtures/on_demand_cluster_fixtures.py, tests/test_resources/test_clusters/cluster_tests.py, tests/test_resources/test_clusters/test_cluster.py, tests/test_resources/test_data/test_package.py, tests/test_resources/test_modules/test_folders/test_packages/test_package.py, tests/test_resources/test_modules/test_functions/test_function.py, tests/test_resources/test_resource_sharing.py, tests/utils.py
* split up `install_packages` into `pip_install`, `conda_install` and `sync_package`
* update logic for locally installed packages - `pip_install` can detect non-editable/non-dev preferred version, but for dev/local editable package versions, should use `sync_package` to rsync over the package + add to path, and then use `pip_install(package)` after to perform the pip install
=> Split up image install_packages

runhouse/resources/packages/package.py
The PR fixes the following edge cases: 
- The extra arguments are wrapped in double brackets: `"runhouse[["server"]]"` -> `"runhouse[server]"`. The extras are wrapped in brackets at the beginning of `_pip_install_cmd()`, therefore they don't need to be wrapped after that. 
- If a specific version is provided, the install cmd was not parsed correctly when extra arguments were passed: `"runhouse==0.0.41[["server"]]"` -> `"runhouse[server]==0.0.41"`.
=> fix installing package with extras

runhouse/resources/hardware/launcher_utils.py
Use new ComputePool-specific endpoints in Den when launching with `pool` configured on a cluster
=> New endpoint for compute pool launches
