run-house/runhouse

CONTRIBUTING.md, README.md
basic contributing w/ dev process, and setting up requirements for testing/docs. welcome suggestions/feedback, and emoji contributions.
=> Add initial CONTRIBUTING.md

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/custom.md, .github/ISSUE_TEMPLATE/feature-request.md
Add bug report and feature request issue templates
=> Add GH issue templates

runhouse/rns/folders/folder.py, runhouse/rns/hardware/cluster.py, tests/test_cluster.py
@dongreenberg I think this is what you meant, instead of the `cluster.on_same_cluster(resource)` that I implemented previously, lmk.
Resolves #33
=> On this cluster function

runhouse/rns/packages/package.py, runhouse/servers/grpc/unary_server.py, tests/test_package.py
Ensure the correct torch version is installed on the cluster, based on its cuda version.
=> Torch version installation on cluster

docs/api/python/run.rst, runhouse/rns/hardware/cluster.py, runhouse/rns/run.py, runhouse/rns/run_module_utils.py, runhouse/servers/http/http_server.py, tests/test_run.py
- Split metadata saved to RNS from Run specific data saved on the system
- Use run factory for loading runs (and creating context manager runs)
=> Runs Loading and Saving Updates

docs/Makefile, docs/conf.py, docs/requirements.txt
- Adds `make json` command to build `.fjson` files for self-hosted Docs
- Updates sphinx libraries
- Conditional options for `json` builds in `conf.py`
=> Adds json operation to docs builder

runhouse/rns/envs/conda_env.py, runhouse/rns/envs/env.py, runhouse/rns/function.py, runhouse/rns/hardware/cluster.py, runhouse/rns/utils/env.py, runhouse/servers/http/http_client.py, runhouse/servers/http/http_server.py, tests/test_env.py
add support for
* conda env servlets
* setting env vars in servlets
=> Env Servlet

docs/tutorials/api/compute.rst
Adds `code-output` class to help with formatting on frontend
=> Adds missing parsed literals classes for UI

runhouse/resources/hardware/cluster.py
Throw a warning if runhouse versions on remote and local don't match. Keep track of and update remote runhouse version every time the server is (re)started, as a simple, BC friendly approach (checking for client rh version is different because it is not being restarted/updated; and checking on the server is finicky and potentially BC-breaking on the server side)
=> Check and warn if local and remote server versions don't match

docs/index.rst, docs/tutorials/api/accessibility.rst, docs/tutorials/api/compute.rst, docs/tutorials/api/data.rst, docs/tutorials/examples/distributed.rst, docs/tutorials/examples/training.rst, docs/tutorials/quick_start.rst, runhouse/scripts/docs/update_rst.py
Adds width and height to img elements to improve docs site performance
=> Adds width and height to img elements in docs

docs/notebooks/examples/distributed.ipynb, docs/tutorials/examples/distributed.rst
Hi, this looks like a typo in the ip address.
Just added `.`
=> A typo in docs

runhouse/docker/slim/Dockerfile, runhouse/servers/http/http_server.py, tests/conftest.py, tests/test_function.py, tests/test_http_server.py, tests/test_obj_store.py
Continuing local docker server work. Also, keep the container running between test runs to save all the build time. All obj store tests pass with docker server. Shoutout to @carolineechen , this cluster takes a password and the password support worked like a charm.
=> Local Docker Server Fixture

runhouse/resources/hardware/cluster.py
We use a global dictionary to cache open ssh connections to particular
addresses. However, for local tests where several connections are running
locally on localhost, the cache would incorrectly hit.
=> Fix global ssh tunnel cache to use port as well.

runhouse/resources/module.py, tests/test_resources/conftest.py, tests/test_resources/test_modules/test_module.py
Added some unittests, for Module methods that were not tested. Also left the testes that ere written as is.
All tests are using docker container cluster. All tests passed.
=> added Module unittests

tests/test_resources/test_clusters/conftest.py, tests/test_resources/test_clusters/test_pwd_cluster.py
`pytest -v` from top level directory now works. Also some minor changes to
nginx cluster.
=> Fix import for mainline pytest and some changes to nginx cluster.

tests/test_resources/test_clusters/conftest.py
pytest -v --level local still passes
=> Refactor cluster file to reuse code.

.github/workflows/all_unit_tests.yaml, setup.py
Note: adds `python-dotenv` to mainline RH installation
=> Add Github Action for top level unit tests.

runhouse/resources/function.py, runhouse/resources/module.py, runhouse/resources/serverless/aws_lambda_function.py, tests/test_resources/test_modules/test_functions/test_aws_lambda/test_aws_lambda.py, tests/test_resources/test_modules/test_functions/test_aws_lambda/test_helpers/lambda_tests/basic_handler_layer.py, tests/test_resources/test_modules/test_functions/test_aws_lambda/test_helpers/lambda_tests/basic_test_handler.py, tests/test_resources/test_modules/test_functions/test_aws_lambda/test_helpers/lambda_tests/call_files_chain/a_special_calc.py, tests/test_resources/test_modules/test_functions/test_aws_lambda/test_helpers/lambda_tests/call_files_chain/sub_file.py, tests/test_resources/test_modules/test_functions/test_aws_lambda/test_helpers/lambda_tests/call_files_chain/sum_file.py, tests/test_resources/test_modules/test_functions/test_aws_lambda/test_helpers/lambda_tests/call_files_separately/a_int_calc.py, tests/test_resources/test_modules/test_functions/test_aws_lambda/test_helpers/lambda_tests/call_files_separately/div_file.py, tests/test_resources/test_modules/test_functions/test_aws_lambda/test_helpers/lambda_tests/call_files_separately/mult_file.py, tests/test_resources/test_modules/test_functions/test_aws_lambda/test_helpers/lambda_tests/call_files_separately/sub_file.py, tests/test_resources/test_modules/test_functions/test_aws_lambda/test_helpers/lambda_tests/call_files_separately/sum_file.py, tests/test_resources/test_modules/test_functions/test_aws_lambda/test_helpers/lambda_tests/requirements.txt, tests/test_resources/test_modules/test_functions/test_aws_lambda/test_lambdas_with_fn.py
Added the ability to send a Runhouse function instance to AWS Lambda. 
Now want to merge it to my "main" lambdas_poc branch in order to work on a single unified branch.
=> [WIP] send rh function instance to AWS Lambda

runhouse/resources/hardware/cluster.py
modifies some of the changes landed by @jlewitt1 in https://app.graphite.dev/github/pr/run-house/runhouse/166/SageMaker-Cluster-updates?utm_source=stack-comment
=> Fix ssh tunnel caching.

runhouse/resources/function.py, runhouse/resources/module.py, tests/test_resources/test_modules/test_module.py
Ensures that we can still call a remote module or function even if the local code isn't present.
Runs with LOCAL and MINIMAL for both test_function and test_module.
=> Add signatures to functions and modules

runhouse/resources/secrets/provider_secrets/azure_secret.py, runhouse/resources/secrets/provider_secrets/gcp_secret.py, runhouse/resources/secrets/provider_secrets/github_secret.py, runhouse/resources/secrets/provider_secrets/huggingface_secret.py, runhouse/resources/secrets/provider_secrets/lambda_secret.py, runhouse/resources/secrets/provider_secrets/sky_secret.py, runhouse/resources/secrets/provider_secrets/ssh_secret.py, runhouse/resources/secrets/utils.py, runhouse/rns/login.py
mostly dealing with secret file loading, plus some cleanup
tests passing with thorough level with these changes, with the refactored test suite in #195
=> Fix some secrets resource bugs

runhouse/__init__.py, runhouse/rns/secrets.py
=> Deprecate (instead of delete) some Secrets APIs instead

runhouse/resources/secrets/secret.py, runhouse/resources/secrets/utils.py, runhouse/rns/login.py
* don't prompt for uploading config if user doesn't have one locally
* secrets vault conversion not fully working so catch an exception for now
=> Login updates

runhouse/resources/hardware/cluster.py, runhouse/resources/module.py, runhouse/resources/resource.py, runhouse/servers/http/http_client.py, runhouse/servers/obj_store.py, tests/test_resources/test_clusters/test_cluster.py, tests/test_resources/test_modules/test_module.py, tests/test_servers/conftest.py, tests/test_servers/test_servlet.py
Refactor Module and Cluster so Module methods can be called without Cluster access. test_module passes with MINIMAL, except final sharing test.
Still TODO:
Add call to obj_store and match obj_store to client API
Update fetch properly
Get sharing test working
=> Module/Cluster client() contract

README.md, runhouse/docker/cuda/Dockerfile, runhouse/docker/slim/password-file-auth/Dockerfile, runhouse/docker/slim/public-key-auth/Dockerfile, runhouse/resources/envs/env.py, runhouse/resources/hardware/cluster.py, runhouse/resources/resource.py, runhouse/resources/secrets/provider_secrets/ssh_secret.py, runhouse/resources/secrets/secret.py, tests/conftest.py, tests/test_resources/test_clusters/test_cluster.py, tests/test_resources/test_resource.py
- Stop copying entire working directory into test containers (!)
- Some Secrets bugfixes
- Some small resource bugfixes
=> A bunch of bugfixes to unblock MINIMAL and LOCAL.

runhouse/resources/folders/folder.py, runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/on_demand_cluster.py, runhouse/resources/hardware/sagemaker_cluster.py, runhouse/resources/hardware/utils.py, tests/fixtures/local_docker_cluster_fixtures.py, tests/test_resources/test_clusters/test_cluster.py, tests/test_resources/test_modules/test_functions/test_function.py
=> Refactor connect_server_client and ssh tunnel logic to be more clear and reusable.

runhouse/servers/nginx/config.py
In GCP Debian default machine images, ufw isn't installed, so the command to open UFW for Nginx fails. This PR skips it if UFW isn't present.
=> Skip opening port in UFW if UFW isn't present

pytest.ini, tests/test_resources/test_clusters/test_multinode_cluster.py, tests/test_resources/test_envs/conftest.py
pytest -s -v --level "thorough" -k "multinodetest" tests
=> run multinode tests with pytest

.github/workflows/unit_tests.yaml, runhouse/resources/hardware/cluster.py, runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py, tests/fixtures/docker_cluster_fixtures.py, tests/test_servers/conftest.py, tests/test_servers/test_http_server.py
To give Den some time to breath.
=> Reduce Unecessary Den calls in CI

runhouse/__init__.py, runhouse/resources/hardware/__init__.py, runhouse/resources/hardware/utils.py, runhouse/servers/cluster_servlet.py, runhouse/servers/http/http_server.py, runhouse/servers/obj_store.py, tests/test_servers/test_http_server.py
Use ray.get to ensure that servlets are initialized before proceeding.
Use Ray for cluster config instead of disk.
=> Change object store initialization sequence.

runhouse/resources/envs/env.py, runhouse/resources/envs/env_factory.py, runhouse/resources/functionals/mapper.py, runhouse/servers/http/http_server.py
Also avoid sending workdir to each replica over and over
=> Use threadpool for mapper.map instead of ray.remote

runhouse/servers/obj_store.py, tests/test_resources/test_modules/test_functions/test_mapper.py
and throw an error if not, to avoid Ray lockup.
=> Check if an env's resources are available before creating the EnvServlet

runhouse/rns/top_level_rns_fns.py
The logic that we previously had to detect if we are on a cluster was extra
tricky because we would initializing the `rh.here` variable upon `import
runhouse as rh`, so there would be circular situations where we need to avoid
deadlocks in Actor creation.
However, now this is almost always being called in a process where one should
easily be able to connect to Ray and get the `cluster_servlet` if it exists. We
don't need any fancy `list_actors` nonsense or an extra `ray.init`.
This is also part of a more general theme of trying to trim down the excess
`ray.init`s that we have in the code to simplify the `ray start` sequence.
=> Simplify `rh.here` Ray cluster detection logic.

tests/test_resources/test_clusters/test_cluster.py
=> Add basic `rh.here` test blocked by `call` working.

runhouse/constants.py, runhouse/main.py, runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/cluster_factory.py
Moving more constants away. Cluster is now free of clutter, somewhat
=> Move remaining constants out of `Cluster` into `constants.py`.

runhouse/resources/hardware/cluster.py
I haven't tested on any machine with `nohup`, however just looking at the code
it seems that if we had flags specified, they would not have been updated in
the `start_nohup_cmd` and they would be omitted.
@RohanSreerama5 to validate and/or test.
=> Add flags to nohup cmd if they are provided.

runhouse/servers/obj_store.py
If we put an env, we ended up storing the Env resource within the Env servlet
for that env, which doesn't really make sense. Changed put_resource to be
similar to put, where you can choose where the resource is stored, and if it
happens to be an env then we create that servlet, however don't necessarily
store it.
You can still simulate that behavior by adding the logic back on the client
side (in cluster.put_resource) that sets env_name to the env if it is one.
=> Fix `put_resource` to not store resource in itself if it is an Env.

runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/cluster_factory.py, runhouse/resources/hardware/on_demand_cluster.py, runhouse/resources/hardware/sagemaker/sagemaker_cluster.py
=> refactor set_connection_defaults() calls for all cluster types

.github/workflows/setup_runhouse/action.yaml, requirements.txt, runhouse/resources/tables/table.py, setup.py, tests/fixtures/docker_cluster_fixtures.py
make pandas, pyarrow optional libraries
add `runhouse[data]` install option
=> Localize data dependency imports

docs/api/cli.rst, runhouse/main.py, runhouse/servers/http/http_server.py, runhouse/servers/obj_store.py, tests/test_resources/test_clusters/test_cluster.py
initial runhouse status
Merge branch 'main' into sb/runhouse-status
=> runhouse status

runhouse/main.py
=> Avoid stopping Ray when running `runhouse stop`.

.github/workflows/setup_runhouse/action.yaml, tests/requirements.txt, tests/test_den/test_defaults.py, tests/test_den/test_rns.py, tests/test_login.py, tests/test_obj_store.py, tests/test_performance.py, tests/test_resources/test_clusters/cluster_tests.py, tests/test_resources/test_clusters/test_pwd_cluster.py, tests/test_resources/test_clusters/test_sagemaker_cluster/test_sagemaker.py, tests/test_resources/test_modules/test_blobs/test_blob.py, tests/test_resources/test_modules/test_folders/test_packages/test_package.py, tests/test_resources/test_modules/test_functions/test_aws_lambda/test_aws_lambda.py, tests/test_resources/test_modules/test_functions/test_function.py, tests/test_resources/test_modules/test_functions/test_mapper.py, tests/test_resources/test_modules/test_module.py, tests/test_resources/test_modules/test_server_modules/dont_test_server_module.py, tests/test_resources/test_modules/test_tables/table_tests.py, tests/test_resources/test_resource.py, tests/test_resources/test_resource_sharing.py, tests/test_resources/test_run.py, tests/test_servers/test_certs.py, tests/test_servers/test_http_client.py, tests/test_servers/test_http_server.py, tests/test_servers/test_nginx.py, tests/test_telemetry.py, tests/test_tutorials.py
removed unittest dependency, now all tests use only pytest.
=> Remove unittest dependency

runhouse/servers/http/http_client.py
When running tests for a while, there are often connections closed from the
server side. Retry these as they seem sporadic.
=> Retry connection errors that can happen when tests run for a while.

runhouse/servers/obj_store.py, tests/test_resources/test_clusters/test_cluster.py
we want to print the key, not the values
=> Print out key instead of value for `runhouse status`.

.github/workflows/local_tests.yaml, pytest.ini, tests/test_resources/test_modules/test_functions/test_function.py, tests/test_resources/test_modules/test_module.py
=> Split tests further to make CI run more parallelized and have less connection errors.

README.md, docs/api/python/cluster.rst, runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py, tests/test_performance.py, tests/test_resources/test_resource_sharing.py
Critical thing here: parsing `query_params` into `CallParams` so that we can set the defaults.
=> Create `get_call` and get rid of old `get_call` and `/call/{module}/{method}` logic.

runhouse/resources/hardware/cluster.py, runhouse/resources/provenance.py, runhouse/servers/http/http_client.py, runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py, runhouse/servers/obj_store.py, tests/test_resources/test_modules/test_functions/test_function.py, tests/test_servers/conftest.py, tests/test_servers/test_certs.py, tests/test_servers/test_http_server.py
We need to flush Caddy's streambuffer for log streaming to work.
=> Fix streaming

runhouse/servers/http/http_utils.py, tests/test_servers/test_servlet.py
just killing `Message` and friends
=> Remove more old HTTP Server <--> Client code.

runhouse/servers/http/http_client.py, runhouse/servers/http/http_server.py
`get_object` was taking a body even though it's a get request. switched up to
be explicit query params.
=> Change `get_object` to actually be a `GET` request and use query params instead of a body.

runhouse/servers/env_servlet.py, tests/test_servers/test_servlet.py
=> Remove `call` method from EnvServlet.

runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py, runhouse/servers/obj_store.py
=> Fix `get_call` so that some of the args are explicit and the rest are parsed as kwargs.

runhouse/logger.py, runhouse/servers/http/http_client.py, runhouse/servers/http/http_utils.py
=> format cluster logs and tracebacks

runhouse/servers/http/http_server.py
Turns out via some profiling Donny did that the `register_activity` call to
suspend autostop is computationally expensive. Trimming it down and only doing
it for clusters where it's actually needed.
=> Fewer `register_activity()` calls and only doing so when there's an autostop to worry about.

examples/sdxl_inf2/README.rst, examples/sdxl_inf2/inf2_sxdl.py, examples/sdxl_inf2/requirements.txt
Example folder with all the things needed to run Stable Diffusion on
Inferentia2.
=> StableDiffusion XL pipeline example.

docs/index.rst, docs/tutorials/getting_started/cloud_quick_start.rst, docs/tutorials/getting_started/den_quick_start.rst, docs/tutorials/getting_started/local_quick_start.rst
corresponding notebook PR: https://github.com/run-house/notebooks/pull/1
=> Add quick start guides

runhouse/servers/http/auth.py
=> Change `AuthCache` to use instance fields instead of class variables.

runhouse/servers/http/http_server.py, tests/fixtures/docker_cluster_fixtures.py
`den_auth` should be on for `TLS` and off for `HTTP`.
=> Change fixtures to correctly have den_auth on and off.

runhouse/resources/envs/utils.py, runhouse/resources/folders/folder.py, runhouse/resources/functionals/mapper.py, runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/on_demand_cluster.py, runhouse/resources/hardware/sky/subprocess_daemon.py, runhouse/resources/module.py, tests/test_resources/test_modules/test_functions/test_mapper.py
squashing and fixing git of: https://app.graphite.dev/github/pr/run-house/runhouse/433/Various-small-bugfixes-for-the-multi-node-mapper
=> All the mapper bugfixes together for real.

examples/llama2/llama2_ec2.py, examples/stable-diffusion-xl-aws-ec2/sdxl.py, examples/stable-diffusion-xl-aws-inferentia2/inf2_sdxl.py
* add h2s
* link out to Runhouse docs where applicable
* move dependency set up to the beginning to make docs a bit cleaner
=> Update `examples` with polish.

tests/test_resources/test_modules/test_module.py
doing this separately from downstack PR to check CI for this only
=> Change `TestModule` to not use clusters for every test.

docs/tutorials/quick-start-den.rst
@carolineechen - found two more problem links. Updated the notebooks and merged that in already.
=> Fix additional docs links

runhouse/resources/module.py, tests/test_resources/test_modules/test_module.py
change the function signature and make it only generate once
=> Change `openapi_spec` function to cache spec.

runhouse/servers/http/http_utils.py
=> Switch serialization back to `None` by default.

runhouse/servers/http/http_server.py
add `/{key}/docs` for Modules. If there is no `openapi_spec` method or the module is not found, we see an error like so:
=> Cluster `/{key}/docs` endpoint for shareable Swagger UI.

tests/conftest.py, tests/fixtures/docker_cluster_fixtures.py, tests/fixtures/secret_fixtures.py, tests/test_servers/conftest.py, tests/test_servers/test_http_client.py
=> Fix flakiness in secret resources by prefixing names with unique testing folder.

tests/test_resources/test_modules/test_functions/test_function.py
=> Save function to a test specific folder for `test_function`.

runhouse/resources/hardware/sky_ssh_runner.py
Submitting this separately from refactoring PR so I can remember that this was causing problems and land it sooner.
=> Fix bug in `SkySSHRunner` with local/remote port ordering.

tests/test_resources/test_clusters/test_cluster.py
=> Change cluster share test to run a command rather than open an ssh connection.

runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/on_demand_cluster.py, runhouse/resources/hardware/sagemaker/sagemaker_cluster.py, runhouse/servers/cluster_servlet.py, runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py
creating background thread to periodically (30s) check whether to update last activity time, if within 5 min of autostop.
=> Fixing cluster autostop

runhouse/utils.py
If we ever need any of these back, we can just find this commit. Mildly useful.
=> Remove other commented out implementations of `sync_function`.

examples/langchain-rag-ec2/langchain_rag.py
Testing out an admonition in the Langchain example - can update the rest after this.
=> Tries example admonition directive

runhouse/servers/obj_store.py
We're seeing many cases where the EnvServlet dies, but it isn't cleaned up from global state. Then, if the user re-runs their code (which may once again call put resource, since it calls `.to`), it'll think the Servlet is already on the machine (because of our global `env_servlets` dict) and not re-create it. This makes the server fully borked after an EnvServlet dies. This is basic fault tolerance to clean up objects if this happens.
=> Change ObjStore methods to call by env servlet name instead of actor.

runhouse/servers/cluster_servlet.py, runhouse/servers/obj_store.py
=> Clean up an `EnvServlet` from global Runhouse daemon state if it dies unexpectedly.

runhouse/servers/obj_store.py
=> Use temporary executor that is cleaned up instead of a long lived ThreadPoolExecutor.

runhouse/resources/hardware/__init__.py, runhouse/resources/hardware/utils.py, runhouse/resources/module.py
=> If we are on the cluster, use the default env for constructing new Modules.

runhouse/resources/module.py
=> Fix error message that prints when a local Runhouse server is not running.

runhouse/servers/http/http_client.py
Disable timeout in httpx.AsyncClient in HttpClient
Formatting
=> Disable timeout in httpx.AsyncClient in HttpClient

runhouse/resources/hardware/on_demand_cluster.py
any reason I can't just do this to start?
further changes to come
=> Don't sync full `.rh` directory to `OnDemandCluster`.

runhouse/rns/defaults.py
Currently getting: 
```Exception: Received [422] from Den PUT 'https://api.run.house/user//config': Failed to update defaults for user.```
=> fix url formatting for user and group config endpoints

docs/tutorials/api-envs.rst
+ corresponding change in tutorials repo
=> Update unnamed env section in docs

tests/requirements.txt
Bug that broke with latest requests release: https://github.com/ansible-collections/community.docker/pull/861
https://github.com/docker/docker-py/issues/3256
=> Fix Docker requests incompatibility in CI.

runhouse/servers/cluster_servlet.py, runhouse/servers/env_servlet.py, runhouse/servers/obj_store.py, runhouse/utils.py
=> Avoid blocking the event loop when calling `status_local` in `EnvServlet`.

tests/test_resources/test_clusters/test_cluster.py
=> Fix caller token propagated test to work for release testing (on demand clusters).

runhouse/servers/http/http_server.py
Saw some changes in [this commit] that messed with the CaddyConfig, causing SSL errors:
```
Shared connection to 54.86.192.143 closed.
/Users/rohinbhasin/work/runhouse/runhouse/servers/http/http_client.py:115: UserWarning: Cert in use (/Users/rohinbhasin/.rh/certs/rh_server.crt) is self-signed, cannot independently verify it.
warnings.warn(
Traceback (most recent call last):
File "/Users/rohinbhasin/miniconda3/envs/rh-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 715, in urlopen
httplib_response = self._make_request(
File "/Users/rohinbhasin/miniconda3/envs/rh-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 404, in _make_request
self._validate_conn(conn)
File "/Users/rohinbhasin/miniconda3/envs/rh-env/lib/python3.9/site-packages/urllib3/connectionpool.py …
```
=> Revert changes to CaddyConfig set up.

runhouse/resources/hardware/on_demand_cluster.py
This gets into a weird state sometimes, adding a safety warning.
=> Add warning to loading OnDemandCluster from sky DB.

tests/fixtures/on_demand_cluster_fixtures.py, tests/test_resources/test_modules/test_functions/test_mapper.py
We should figure out what we're doing for unnamed envs here.
=> Use a named env for multinode cluster test.

tests/fixtures/on_demand_cluster_fixtures.py, tests/test_resources/test_clusters/test_cluster.py
* Initialize the envs in the test that they're actually used in
Tested: `pytest -v --level release -k "multinode"`
=> Update multinode cluster fixtures.

runhouse/servers/cluster_servlet.py, setup.py
Needs to be tested with RELEASE level, unit isn't enough.
=> Bump Sky Version and Fix Sky Install on Start

runhouse/resources/hardware/cluster.py
conda run command did not parse bash command well and would fail to execute command to write to config.yaml
=> Save config.yaml properly for conda env

runhouse/__init__.py
=> Bump version to 0.0.31

runhouse/resources/envs/env.py, runhouse/resources/envs/utils.py, runhouse/resources/hardware/cluster.py, runhouse/resources/packages/package.py
use `conda run -n <env_name> $SHELL shelx.quote(user_command)` to better handle bash commands
=> Update conda env run commands

runhouse/resources/envs/env.py, tests/fixtures/docker_cluster_fixtures.py, tests/fixtures/on_demand_cluster_fixtures.py
Higher Ray version in local tests and both higher Ray version and alternate Python version in release tests
=> Test default envs more aggressively

examples/llama3-8b-tgi-ec2/README.md, examples/llama3-8b-tgi-ec2/llama3_tgi_ec2.py, examples/llama3-8b-tgi-ec2/requirements.txt
Adds a new example of running Llama 3 with TGI on AWS based on the Llama 2 example
=> Llama 3 TGI Example

docs/tutorials/api-modules.rst
Corresponding notebooks PR: https://github.com/run-house/notebooks/pull/19
=> update api module class example

tests/test_resources/test_clusters/test_on_demand_cluster.py
* skip test that terminates the cluster
* relax time constraint for autostop
=> Small test fixes

runhouse/constants.py
runhouse ray not being fully terminated prior to starting ray again sometimes causing problems`
=> Update ray stop command

runhouse/resources/resource.py
handling mismatch in open ports bc of string v int
=> Update alt options check

docs/index.rst, docs/installation.rst
Meant to be a page we can easily link to in the introduction of any tutorial - so we don't find ourselves repeating all the installation steps over and over.
Are there any "gotchas" I missed here?
=> Docs installation page

runhouse/resources/hardware/utils.py, tests/test_resources/test_clusters/test_on_demand_cluster.py
Making ResourceServerStatus to match the ResourceServerStatus in Den.
=> modify resouce status schema

.github/workflows/nightly_release_testing.yaml, .github/workflows/setup_release_testing/action.yaml
Starting with AWS, to add GCP and K8s
=> add initial nightly release testing

docs/tutorials/api-clusters.rst, docs/tutorials/quick-start-den.rst
https://github.com/run-house/notebooks/pull/21
=> Add up if not to clusters in tutorials

runhouse/__init__.py, runhouse/resources/folders/__init__.py, runhouse/resources/folders/folder.py, runhouse/resources/packages/__init__.py, runhouse/resources/packages/package.py
A user should be able to sync a Folder that is their home directory if they want. Just not a Package that has their home directory and gets installed.
=> Raise `CodeSyncError` at Package level, not at Folder level.

runhouse/resources/functions/function_factory.py, runhouse/resources/module.py
=> Check if `env` is actually an `Env` object before attempting to add pointers.

docs/installation.rst
=> Fix broken link in installation doc

runhouse/constants.py, runhouse/main.py
=> Revert use of -9 in restart server

docs/installation.rst
=> Clarify cloud provider optionality in installation docs

runhouse/servers/obj_store.py
There could be secrets in there.
=> Don't log full config in put_resource

.github/workflows/generate_docs_for_tag.yaml, scripts/generating_docs.py
Build docs for tag upon creation, or manually for a specific tag
=> Action for release tag docs

runhouse/resources/hardware/utils.py
related Den PR: https://github.com/run-house/runhouse-den/pull/361
=> remove unused status from ResourceServerStatus enum

examples/pytorch_distributed/pytorch_distributed.py, examples/pytorch_distributed/requirements.txt
Basic PyTorch Distributed Example
PyTorch distributed example
=> Basic PyTorch Distributed Example

runhouse/servers/http/http_client.py, runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py, tests/test_resources/test_modules/test_functions/test_function.py, tests/test_servers/test_http_client.py, tests/test_servers/test_http_server.py
=> Pass `run_name` from client side, enforce requirement server side, and ensure uniqueness.

runhouse/servers/http/http_client.py
=> Consolidate logic between `acall_module_method` and `call_module_method`.

runhouse/constants.py
=> Fix conda install command on cluster

docs/tutorials/api-clusters.rst
Add a brief description that you can launch within VPCs on the Clusters page.
=> Add VPC mention

runhouse/resources/hardware/on_demand_cluster.py
removed the den_auth check, cause now each cluster which was created by a user with runhouse token we send status updated to den.
=> update cluster.teardown() logic

runhouse/main.py
Note: some of the consoles (Pycharm console for example) do not have support for clickable hyperlinks. Therefore, in such consoles, the cluster name will be printed as a simple text.
=> status cmd prints cluster name as hyperlink to den

tests/test_resources/test_clusters/test_cluster.py
accounts for cluster tokens now being ephemeral
=> update token propagate test for new token generation flow

runhouse/servers/env_servlet.py, tests/test_resources/test_clusters/test_cluster.py
CI will pass once [den change](https://github.com/run-house/runhouse-den/pull/385) will be deployed on den-prod
=> add node index to cluster status output

runhouse/resources/hardware/cluster.py, runhouse/servers/http/http_client.py, runhouse/servers/http/http_server.py, runhouse/servers/http/http_utils.py
=> Add endpoints to interact with processes on cluster.

tests/test_resources/test_clusters/test_cluster.py
=> Basic test for creating and listing processes via cluster helper function.

runhouse/resources/packages/package.py
=> Change `Package` installation to be global instead of in that process only.

runhouse/resources/hardware/cluster.py, runhouse/servers/http/http_client.py, runhouse/servers/http/http_server.py, tests/test_servers/test_http_client.py
fixes function test breakage: https://github.com/run-house/runhouse/actions/runs/10547208876/job/29219605694?pr=1195
=> async client error handling + auth updates

runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/launcher_utils.py, runhouse/resources/hardware/on_demand_cluster.py
- Updates logic to teardown clusters via Den
- Successfully completes the teardown but has an error on saving the cluster after
- May need to move the saving step to Den
=> Updates cluster teardown via Den

runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/launcher_utils.py, runhouse/resources/hardware/on_demand_cluster.py, runhouse/utils.py
Updates the DenLauncher and LocalLauncher classes to use classmethods for up and teardown. This allows for moving more cluster updating logic into the launchers from the OnDemandCluster
Also:
- Adds a spinner to show in logs during "info_spinner" events
=> Refactor Launchers with class methods

runhouse/resources/hardware/__init__.py, runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/launcher_utils.py, runhouse/resources/hardware/on_demand_cluster.py, runhouse/resources/hardware/utils.py, runhouse/utils.py
Allows for launching clusters via Den with streaming logs, WIP
=> Launch cluster from Den with streaming logs

examples/pytorch/resnet_training.py
Add Paul's Resnet Training
Add Paul's Resnet training
=> Add Paul's Resnet Training

runhouse/resources/hardware/cluster_factory.py, runhouse/resources/hardware/on_demand_cluster.py
I think the naming was a little off in the deprecation warning - quick fix
=> Fix num_instances to num_nodes

runhouse/servers/obj_store.py, runhouse/servers/servlet.py, tests/test_resources/test_modules/test_module.py
Stream logs for nested module calls
Stream logs for nested module calls
=> Stream logs for nested module calls

docs/how-to-use-runhouse.rst, docs/runhouse-in-your-stack.rst, docs/tutorials/api-resources.rst, docs/tutorials/quick-start-cloud.rst, docs/tutorials/quick-start-den.rst
including Den launcher argument + more changes to content
=> Docs edits - Nov 11-12th

runhouse/servers/cluster_servlet.py, runhouse/servers/http/http_server.py, runhouse/servers/obj_store.py, runhouse/servers/servlet.py, tests/test_servers/test_server_obj_store.py, tests/utils.py
will be used for replication of processes/envs later.
=> Store initialization arguments for Process/Env in ClusterServlet.

runhouse/servers/http/http_server.py, runhouse/servers/obj_store.py, runhouse/servers/servlet.py
`get_servlet(..., create=True)`.
=> Wait for actor to actually initialize before returning from `get_servlet(..., create=True)`.

runhouse/resources/hardware/cluster.py
IP lists can be None in clusters but often assumed that it is an array
=> Gracefully handle empty IP lists

runhouse/resources/hardware/on_demand_cluster.py
Will be useful for enforcing resource quotas / limits
=> add additional fields to ondemand launched_properties

runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/launcher_utils.py, runhouse/resources/hardware/on_demand_cluster.py, runhouse/servers/obj_store.py, runhouse/servers/servlet.py, tests/test_resources/test_clusters/test_on_demand_cluster.py
set ips inside and when determining launch properties, and access cluster.ips through that since it's not something that we should be able to set and modify
=> Move ips into launched properties attribute

runhouse/resources/hardware/launcher_utils.py
=> add log spinner when setting up the cluster

runhouse/resources/hardware/launcher_utils.py, runhouse/servers/http/http_utils.py, runhouse/utils.py
=> update launcher formatting to match formatting used for streaming rh daemon logs

runhouse/cli_utils.py, runhouse/main.py, runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/utils.py, runhouse/rns/top_level_rns_fns.py, runhouse/servers/http/http_server.py, tests/test_resources/test_clusters/test_cluster.py
=> Change `default_env_name` to `default_process_name` in HTTPServer initialization.

runhouse/resources/hardware/on_demand_cluster.py, runhouse/resources/hardware/utils.py, runhouse/servers/cluster_servlet.py, tests/fixtures/docker_cluster_fixtures.py, tests/test_resources/test_clusters/test_cluster.py, tests/test_resources/test_clusters/test_on_demand_cluster.py, tests/utils.py
to more clearly differentiate with `cluster_status`
=> replace `status` with `daemon_status`

runhouse/resources/hardware/cluster.py, runhouse/resources/module.py, runhouse/servers/http/http_server.py, runhouse/servers/obj_store.py
Update PyTorch distribution approach
Update PyTorch distribution approach
=> Fix list_processes when on the cluster

examples/pytorch/resnet_training.py, runhouse/resources/distributed/pytorch_distributed.py, runhouse/resources/envs/env.py, runhouse/resources/hardware/cluster_factory.py
Fix pytorch resnet training
Fix pytorch resnet training
=> Fix pytorch resnet training

examples/flux/flux.py, runhouse/resources/hardware/cluster_factory.py, runhouse/resources/hardware/on_demand_cluster.py
Add new cluster resource args
Update flux example
=> Add new cluster resource args

runhouse/resources/hardware/cluster.py, runhouse/resources/module.py, runhouse/servers/http/http_server.py, runhouse/servers/obj_store.py, runhouse/servers/servlet.py, tests/utils.py
Didn't like how this was named two different things depending on where you were. Renamed for clarity
=> Change `process_init_args` to `create_process_params`.

docs/api/python/secrets.rst, runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/on_demand_cluster.py, runhouse/resources/images/image.py, runhouse/resources/secrets/provider_secrets/docker_secret.py, runhouse/resources/secrets/provider_secrets/providers.py
include machine image id option in Image init
=> Add base machine image support to Image class

runhouse/cli_utils.py, runhouse/resources/hardware/cluster.py, runhouse/resources/hardware/utils.py
@carolineechen wdyt of labeling -1 as "Disabled"? was thinking also "Suspended"
=> add autostop to cluster list CLI output

runhouse/cli_utils.py, tests/test_resources/test_clusters/test_cluster.py
=> delete runhouse.Env from cluster status cli output

runhouse/resources/hardware/cluster_factory.py, runhouse/resources/hardware/on_demand_cluster.py
bug fixing for now but more comprehensive factory refactoring to follow
=> Properly override allowed cluster factory arguments

runhouse/main.py
something broke with the ssh flow of a local (docker) ondemand cluster that isn't saved, with loading the ssh proxy command from a generated sky config. 
can just directly call `ssh <cluster_name>`, sky sets up the ssh config already and it should flow. no longer running into the previous need to call `conda deactivate` for docker images either
=> Update cluster ssh

examples/llama3-vllm-gcp/llama3_vllm_gcp.py
In tandem with updating the Llama 3 blog post
=> Cleanup vLLM GCP example

docker/slim/public-key-auth/instructions.md
beauty the markdown code info.
=> beauty the markdown code info.

runhouse/resources/hardware/cluster.py
match the `run_bash` output to the command input type
=> Update run bash output

tests/test_resources/test_clusters/test_cluster.py
Motivation to this PR:
The way we are setting BYO clusters for clusters now (static_cpu_pwd_cluster),t he internal ips list equals the external ips, since we are spinning up an ec2 under the hood -> we can't run the run_bash. (we are getting "invalid internal ip" error)
=> Fix cluster nightly release failures

runhouse/resources/hardware/cluster.py
with current docs setup, if a function doesnt have docstrings it won't show up on docs. can discuss if we want to keep that behavior or not
=> Add docstrings to cluster process functions

runhouse/main.py
=> update logs cli cmd to more clearly denote cluster logs

runhouse/servers/cluster_servlet.py
fix gpu utilization collection
=> fix gpu utilizataion colllection

runhouse/resources/images/image.py
correctly serialize image if it contains secret objects (and not just provider strings) inside a sync_secrets step
=> Compute config for image secrets

runhouse/resources/hardware/launcher_utils.py, runhouse/utils.py
=> show completed steps in launch flow

runhouse/cli_utils.py, runhouse/resources/hardware/utils.py, tests/test_resources/test_clusters/test_cluster.py
depends on [#552](https://github.com/run-house/runhouse-den/pull/552) den PR
=> by default, cluster list returns all clusters owned by the user

runhouse/resources/hardware/launcher_utils.py, runhouse/resources/hardware/on_demand_cluster.py, runhouse/resources/hardware/utils.py, runhouse/utils.py
=> Prettify post launch prints

runhouse/resources/module.py, tests/test_resources/test_clusters/test_cluster.py
=> Create a new process with random name for every new module or function put.

runhouse/servers/cluster_servlet.py, runhouse/servers/node_servlet.py, runhouse/servers/obj_store.py, runhouse/servers/servlet.py, runhouse/utils.py, tests/test_resources/test_clusters/test_cluster.py
CI is passing after additional changes made in the stack, see #1752
=> Collect gpu metrics for multinode

runhouse/cli_utils.py, runhouse/main.py
CI is passing after additional changes made in the stack, see #1752 
Default output (no node is provided):
Output when a node is provided:
output when a wrong node ip / index is provided (an ip which is not associated with the cluster):
=> Cluster status cli cmd output for multinode clusters

runhouse/cli_utils.py, runhouse/constants.py
=> cluster status cli: print running time for any callable resource on the cluster
